// GENERATED by scripts/gen-groups.mjs — do not edit; rerun the script.
import { urls, type UrlPatterns } from "@rangojs/router";

export const hubPatterns: UrlPatterns<any> = urls(({ include }) => [
  include("/g001", () => import("./group-001.js"), {
    name: "g001",
  }),
  include("/g002", () => import("./group-002.js"), {
    name: "g002",
  }),
  include("/g003", () => import("./group-003.js"), {
    name: "g003",
  }),
  include("/g004", () => import("./group-004.js"), {
    name: "g004",
  }),
  include("/g005", () => import("./group-005.js"), {
    name: "g005",
  }),
  include("/g006", () => import("./group-006.js"), {
    name: "g006",
  }),
  include("/g007", () => import("./group-007.js"), {
    name: "g007",
  }),
  include("/g008", () => import("./group-008.js"), {
    name: "g008",
  }),
  include("/g009", () => import("./group-009.js"), {
    name: "g009",
  }),
  include("/g010", () => import("./group-010.js"), {
    name: "g010",
  }),
  include("/g011", () => import("./group-011.js"), {
    name: "g011",
  }),
  include("/g012", () => import("./group-012.js"), {
    name: "g012",
  }),
  include("/g013", () => import("./group-013.js"), {
    name: "g013",
  }),
  include("/g014", () => import("./group-014.js"), {
    name: "g014",
  }),
  include("/g015", () => import("./group-015.js"), {
    name: "g015",
  }),
  include("/g016", () => import("./group-016.js"), {
    name: "g016",
  }),
  include("/g017", () => import("./group-017.js"), {
    name: "g017",
  }),
  include("/g018", () => import("./group-018.js"), {
    name: "g018",
  }),
  include("/g019", () => import("./group-019.js"), {
    name: "g019",
  }),
  include("/g020", () => import("./group-020.js"), {
    name: "g020",
  }),
  include("/g021", () => import("./group-021.js"), {
    name: "g021",
  }),
  include("/g022", () => import("./group-022.js"), {
    name: "g022",
  }),
  include("/g023", () => import("./group-023.js"), {
    name: "g023",
  }),
  include("/g024", () => import("./group-024.js"), {
    name: "g024",
  }),
  include("/g025", () => import("./group-025.js"), {
    name: "g025",
  }),
  include("/g026", () => import("./group-026.js"), {
    name: "g026",
  }),
  include("/g027", () => import("./group-027.js"), {
    name: "g027",
  }),
  include("/g028", () => import("./group-028.js"), {
    name: "g028",
  }),
  include("/g029", () => import("./group-029.js"), {
    name: "g029",
  }),
  include("/g030", () => import("./group-030.js"), {
    name: "g030",
  }),
  include("/g031", () => import("./group-031.js"), {
    name: "g031",
  }),
  include("/g032", () => import("./group-032.js"), {
    name: "g032",
  }),
  include("/g033", () => import("./group-033.js"), {
    name: "g033",
  }),
  include("/g034", () => import("./group-034.js"), {
    name: "g034",
  }),
  include("/g035", () => import("./group-035.js"), {
    name: "g035",
  }),
  include("/g036", () => import("./group-036.js"), {
    name: "g036",
  }),
  include("/g037", () => import("./group-037.js"), {
    name: "g037",
  }),
  include("/g038", () => import("./group-038.js"), {
    name: "g038",
  }),
  include("/g039", () => import("./group-039.js"), {
    name: "g039",
  }),
  include("/g040", () => import("./group-040.js"), {
    name: "g040",
  }),
  include("/g041", () => import("./group-041.js"), {
    name: "g041",
  }),
  include("/g042", () => import("./group-042.js"), {
    name: "g042",
  }),
  include("/g043", () => import("./group-043.js"), {
    name: "g043",
  }),
  include("/g044", () => import("./group-044.js"), {
    name: "g044",
  }),
  include("/g045", () => import("./group-045.js"), {
    name: "g045",
  }),
  include("/g046", () => import("./group-046.js"), {
    name: "g046",
  }),
  include("/g047", () => import("./group-047.js"), {
    name: "g047",
  }),
  include("/g048", () => import("./group-048.js"), {
    name: "g048",
  }),
  include("/g049", () => import("./group-049.js"), {
    name: "g049",
  }),
  include("/g050", () => import("./group-050.js"), {
    name: "g050",
  }),
]);

export default hubPatterns;
