// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/app/about",
  "blog.index": "/app/blog",
  "blog.post": "/app/blog/:slug",
  home: "/app",
  "loaderTypes.nullCached": "/app/loader-types/null-cached",
  "loaderTypes.nullNonCached": "/app/loader-types/null-non-cached",
  "loaderTypes.reactNodeCached": "/app/loader-types/react-node-cached",
  "loaderTypes.reactNodeNonCached": "/app/loader-types/react-node-non-cached",
  "shop.cart": "/app/shop/cart",
  "shop.index": "/app/shop",
  "shop.product": "/app/shop/product/:productId",
} as const;

declare global {
  namespace RSCRouter {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
