// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/app/about",
  "blog.index": "/app/blog",
  "blog.post": "/app/blog/:slug",
  home: "/app",
  "loaderTypes.nullCached": "/app/loader-types/null-cached",
  "loaderTypes.nullNonCached": "/app/loader-types/null-non-cached",
  "loaderTypes.reactNodeCached": "/app/loader-types/react-node-cached",
  "loaderTypes.reactNodeNonCached": "/app/loader-types/react-node-non-cached",
  "shop.cart": "/app/shop/cart",
  "shop.index": "/app/shop",
  "shop.product": "/app/shop/product/:productId",
} as const;

// Aliased so the augmentation below does not pay a homomorphic mapped-type
// instantiation per route; `as const` already makes the members readonly.
type NamedRoutesShape = typeof NamedRoutes;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends NamedRoutesShape {}
  }
}
