// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/about",
  "blog.index": "/blog",
  "blog.post": "/blog/:slug",
  home: "/",
  "shop.cart": "/shop/cart",
  "shop.index": "/shop",
  "shop.product": "/shop/product/:productId",
} as const;

declare global {
  namespace RSCRouter {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
