// Auto-generated by @rangojs/router - do not edit
export const routes = {
  prefetchScopeHome: "/",
  prefetchScopeResourceRoute: "/target.js",
  prefetchScopeStreamHang: "/stream-hang",
  prefetchScopeTarget: "/target",
} as const;
export type routes = typeof routes;
