packages:
  - 'packages/*'
  - 'packages/rsc-router/e2e/test-app'
  - 'packages/rangojs-router/e2e/test-app'
  - 'packages/rangojs-router/e2e/e2e-basic'
  - 'examples/*'
  - 'apps/*'

catalog:
  "@vitejs/plugin-rsc": ^0.5.14
  react: ^19.2.1
  react-dom: ^19.2.1
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  vite: ^7.3.0
