// Auto-generated by @rangojs/router - do not edit
export const routes = {
  detail: "/:slug",
  index: "/",
  raw: "/:slug/raw",
  refDetail: "/ref/:slug",
  refIndex: "/ref",
  search: "/api/search",
} as const;
export type routes = typeof routes;
