// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  home: "/",
  "timeout.fastRender": "/timeout/fast-render",
  "timeout.fastResponse": "/timeout/fast-response",
  "timeout.slowAction": "/timeout/slow-action",
  "timeout.slowRender": "/timeout/slow-render",
  "timeout.slowResponse": "/timeout/slow-response",
} as const;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
