"use server";

/**
 * Generic server action dispatcher for fetchable loaders.
 *
 * This is a "use server" MODULE — the RSC plugin registers all exports in
 * the action manifest (server env) and creates createServerReference() proxies
 * (client env). This makes it callable from the client as a real server action.
 *
 * Client-side loader stubs (generated by the Vite plugin) import this and
 * wrap it per-loader: (prev, fd) => invokeFetchableLoaderAction(id, prev, fd).
 * The wrapper calls this server reference, which React dispatches to the server.
 *
 * The RSC virtual entry must import this module with a NAMED import so the
 * RSC build traverses and discovers it. A bare side-effect import is NOT
 * enough — the RSC plugin skips modules it doesn't traverse to.
 *
 * On the server, route params (e.g. slug) come from requestContext.params,
 * which is set by setRequestContextParams() before the action executes.
 */

import { executeLoaderAction } from "./loader-action-shared.js";

export async function invokeFetchableLoaderAction(
  loaderId: string,
  _prevState: unknown,
  formData: FormData,
): Promise<unknown> {
  return executeLoaderAction(loaderId, formData);
}
