"use server";

/**
 * Generic server action for fetchable loaders.
 *
 * Imported by client-side loader stubs generated by the Vite plugin.
 * When a client component directly imports a fetchable loader, the
 * plugin generates a stub that calls this action to dispatch the
 * loader on the server.
 *
 * The "use server" directive makes the RSC bundler create a server
 * reference for the client and execute the actual function on the server.
 */

import { executeLoaderAction } from "./loader-action-shared.js";

export async function invokeFetchableLoaderAction(
  loaderId: string,
  _prevState: unknown,
  formData: FormData,
): Promise<unknown> {
  return executeLoaderAction(loaderId, formData);
}
