import { missingInjectedIdError } from "./missing-id-error.js";
import { isUnderTestRunner } from "./runtime-env.js";

/**
 * Handle definition for accumulating data across route segments.
 *
 * Handles allow server-side route handlers to pass accumulated data to client
 * components. Unlike loaders (which fetch data for specific routes), handles
 * accumulate data across all matched route segments.
 *
 * @example
 * ```ts
 * // Define a handle (name auto-generated from file + export).
 * // Default collect is the identity: one array per segment that pushed.
 * export const Breadcrumbs = createHandle<BreadcrumbItem, BreadcrumbItem[]>(
 *   (segments) => segments.flat(), // opt into a single flat list
 * );
 *
 * // Use in handler
 * const push = ctx.use(Breadcrumbs);
 * push({ label: "Home", href: "/" });
 *
 * // Consume on client
 * const crumbs = useHandle(Breadcrumbs);
 * ```
 */
export interface Handle<TData, TAccumulated = TData[][]> {
  /**
   * Brand to distinguish handles from loaders in ctx.use()
   */
  readonly __brand: "handle";

  /**
   * Auto-generated unique ID for this handle (used as key in storage)
   * Format: "filePath#ExportName" in dev, "hash#ExportName" in production
   */
  readonly $$id: string;
}

/**
 * Default collect: pass the per-segment data through as-is — one array per segment
 * that pushed, in segment order. Lossless, so a consumer can tell which/how-many
 * segments contributed. Callers that want a single flat list opt in with
 * `createHandle((segments) => segments.flat())`.
 */
function defaultCollect<T>(segments: T[][]): T[][] {
  return segments;
}

// Module-level registry mapping $$id to collect functions.
// Populated when createHandle() runs (both server and client).
// Used by useHandle() to recover collect when handle is deserialized from RSC prop.
const collectRegistry = new Map<string, (segments: unknown[][]) => unknown>();

// Monotonic counter for runtime fallback ids (see createHandle). Only used
// when no build id was injected (a bare unit test).
let runtimeHandleIdCounter = 0;

export function getCollectFn(
  id: string,
): ((segments: unknown[][]) => unknown) | undefined {
  return collectRegistry.get(id);
}

/**
 * Create a handle definition for accumulating data across route segments.
 *
 * The $$id is auto-generated by the Vite exposeInternalIds plugin based on
 * file path and export name. No manual naming required.
 *
 * @param collect - Optional collect function. Default: pass the per-segment data
 *   through as-is (one array per segment that pushed, in segment order). Lossless,
 *   so a consumer can tell which/how-many segments contributed. Opt into a single
 *   flat list with `(segments) => segments.flat()`.
 * @param __injectedId - Auto-injected by Vite plugin, do not provide manually
 *
 * @example
 * ```ts
 * // Default: per-segment grouping, as-is
 * export const Pushed = createHandle<string>();
 * // Result type: string[][]  (e.g. [["a"], ["b", "c"]])
 *
 * // Opt into a single flat list
 * export const Breadcrumbs = createHandle<BreadcrumbItem, BreadcrumbItem[]>(
 *   (segments) => segments.flat()
 * );
 * // Result type: BreadcrumbItem[]
 *
 * // Custom: last value wins
 * export const PageTitle = createHandle<string, string>(
 *   (segments) => segments.flat().at(-1) ?? "Default Title"
 * );
 * // Result type: string
 *
 * // Custom: object merge
 * export const Meta = createHandle<Partial<MetaTags>, MetaTags>(
 *   (segments) => Object.assign({ robots: "index,follow" }, ...segments.flat())
 * );
 * // Result type: MetaTags
 *
 * // Custom: dedupe by href (TAccumulated must be given — a custom collect that
 * // returns a flat array no longer matches the default TData[][])
 * export const Breadcrumbs = createHandle<BreadcrumbItem, BreadcrumbItem[]>(
 *   (segments) => {
 *     const all = segments.flat();
 *     return all.filter((item, i) => all.findIndex(x => x.href === item.href) === i);
 *   }
 * );
 * ```
 */
export function createHandle<TData, TAccumulated = TData[][]>(
  collect?: (segments: TData[][]) => TAccumulated,
  __injectedId?: string,
): Handle<TData, TAccumulated> {
  let handleId = __injectedId ?? "";

  // No build-injected id. Under a test runner: fall back to a synthetic id so the
  // collect registers below and the handle is exercisable in tests (useHandle,
  // collectHandle, renderRoute's `handles` run the REAL collect). Otherwise (dev
  // or a real build) it means an UNSUPPORTED handler shape the plugin skipped —
  // fail loud. The rich, stack-parsing diagnostic stays behind the NODE_ENV check
  // so a production build folds it away and tree-shakes missing-id-error.ts out,
  // shipping the small throw instead. isUnderTestRunner() is runtime-safe.
  if (!handleId) {
    if (isUnderTestRunner()) {
      handleId = `__rango_runtime_handle_${runtimeHandleIdCounter++}`;
    } else if (process.env.NODE_ENV !== "production") {
      throw missingInjectedIdError("Handle", "createHandle");
    } else {
      throw new Error(
        "[rango] Handle is missing $$id — the build plugin did not inject one. " +
          "Export it as `export const X = createHandle(...)`.",
      );
    }
  }

  const collectFn =
    collect ??
    (defaultCollect as unknown as (segments: TData[][]) => TAccumulated);

  collectRegistry.set(
    handleId,
    collectFn as (segments: unknown[][]) => unknown,
  );

  return {
    __brand: "handle" as const,
    $$id: handleId,
  };
}

export function isHandle(value: unknown): value is Handle<unknown, unknown> {
  return (
    typeof value === "object" &&
    value !== null &&
    "__brand" in value &&
    (value as { __brand: unknown }).__brand === "handle"
  );
}

/**
 * Collect handle data from a HandleData map, applying the handle's collect
 * function over segments in order. Shared between server-side rendered()
 * reads and client-side useHandle().
 *
 * @param handle - The handle to collect data for
 * @param data - Full handle data map (handleName -> segmentId -> entries[])
 * @param segmentOrder - Segment IDs in parent -> child resolution order
 */
export function collectHandleData<TData, TAccumulated>(
  handle: Handle<TData, TAccumulated>,
  data: Record<string, Record<string, unknown[]>>,
  segmentOrder: string[],
): TAccumulated {
  // Fall back to the default (identity, pass-through) collect when none is
  // registered — e.g. the handle's module was not imported so createHandle() never
  // ran. This is harmless for a handle that wanted the default, but a handle with a
  // CUSTOM collect that failed to register silently gets the wrong shape (identity
  // TData[][]) cast as its declared TAccumulated. The runtime can't tell the two
  // apart (a Handle only carries $$id), so warn in dev (folded out of production).
  const collectFn = getCollectFn(handle.$$id);
  if (!collectFn && process.env.NODE_ENV !== "production") {
    console.warn(
      `[rango] Handle "${handle.$$id}" has no registered collect — falling back ` +
        `to the identity (per-segment data as-is). If this handle declares a ` +
        `CUSTOM collect, import its module so createHandle() runs where it is read.`,
    );
  }
  const collect = (collectFn ??
    (defaultCollect as unknown as (segments: unknown[][]) => unknown)) as (
    segments: TData[][],
  ) => TAccumulated;

  const segmentData = data[handle.$$id];
  if (!segmentData) return collect([]);

  const segmentArrays: TData[][] = [];
  for (const segmentId of segmentOrder) {
    const entries = segmentData[segmentId];
    if (entries && entries.length > 0) {
      segmentArrays.push(entries as TData[]);
    }
  }
  return collect(segmentArrays);
}
