/**
 * Route name utilities for filtering internal route names.
 *
 * Internal names stay active in the runtime manifest for matching and local
 * reverse() resolution, but they must not leak into public APIs or generated
 * route maps.
 */

export const AUTO_GENERATED_ROUTE_PREFIX = "$path_";
export const INTERNAL_INCLUDE_SCOPE_PREFIX = "$prefix_";

/**
 * Check if a route name is internal.
 * Internal names include:
 * - unnamed path() routes like "$path__health" or "docs.$path__health"
 * - hidden include scopes like "$prefix_0.index" or "blog.$prefix_1.post"
 *
 * User-defined names containing "$" (e.g. "docs.$admin") are valid and must
 * be preserved.
 */
export function isAutoGeneratedRouteName(name: string): boolean {
  return name.split(".").some((segment) => {
    return (
      segment.startsWith(AUTO_GENERATED_ROUTE_PREFIX) ||
      segment.startsWith(INTERNAL_INCLUDE_SCOPE_PREFIX)
    );
  });
}
