/**
 * transition({ when }) references: what a route definition may carry as a
 * `when`, how definitions are validated, and how the browser turns the carried
 * value back into a callable predicate.
 *
 * `when` is a BROWSER predicate. The server never calls it; it only carries it
 * to the browser inside the segment's transition config, as one of:
 *
 * - a React client reference: a function exported from a `"use client"`
 *   module and imported into a server `urls()` file, or an inline literal the
 *   build hoisted into one (vite/plugins/transition-when-hoist.ts). Flight
 *   serializes it as a module reference and the browser resolves it to the
 *   real function;
 * - a clientUrls() when reference, synthesized by the projection materializer
 *   (client-urls/server-projection.ts): the group's definition client
 *   reference plus the route id. The browser resolves it to the `when` the
 *   route declared in its `"use client"` module.
 *
 * A plain function (a server function) cannot cross Flight, and a
 * non-function is never callable. Both are LOUD errors: route discovery
 * (generateManifestFull `validateTransitionWhen`) fails dev startup, the
 * build and HMR re-discovery, and attachTransitionWhen (rsc/) throws the same
 * error at render time for a route discovery did not see.
 *
 * Telling a client reference apart from a server function needs the
 * react-server module graph, where a `"use client"` import IS a client
 * reference. Outside it (a node/DOM unit-test project that aliases the router
 * entry) the import is the plain function, so strict validation is enabled
 * only by the Vite plugin: discovery passes the option, and the generated
 * routes-manifest module calls enableTransitionWhenValidation() in the app's
 * RSC realm (vite/discovery/virtual-module-codegen.ts).
 */

import { isAutoGeneratedRouteName } from "./route-name.js";
import type { TransitionWhenFn } from "./types/segments.js";

const CLIENT_REFERENCE = Symbol.for("react.client.reference");

/** String key, so the marker survives Flight (symbol keys are not serialized). */
const CLIENT_URLS_WHEN_KEY = "__rangoClientUrlsWhen";

interface ClientUrlsWhenRef {
  readonly __rangoClientUrlsWhen: 1;
  /** The clientUrls() definition: a client reference on the server, the definition object in the browser. */
  readonly definition: unknown;
  readonly routeId: string;
}

export function isClientReference(value: unknown): boolean {
  if (typeof value !== "function" && (typeof value !== "object" || !value)) {
    return false;
  }
  return (value as { $$typeof?: unknown }).$$typeof === CLIENT_REFERENCE;
}

function isClientUrlsWhenRef(value: unknown): value is ClientUrlsWhenRef {
  return (
    typeof value === "object" &&
    value !== null &&
    (value as Record<string, unknown>)[CLIENT_URLS_WHEN_KEY] === 1
  );
}

export function createClientUrlsWhenRef(
  definition: unknown,
  routeId: string,
): TransitionWhenFn {
  const ref: ClientUrlsWhenRef = {
    __rangoClientUrlsWhen: 1,
    definition,
    routeId,
  };
  return ref as unknown as TransitionWhenFn;
}

let strictValidation = false;

/**
 * Turn on server-function rejection for this realm. Called by the Vite
 * plugin's generated routes-manifest module, never by tests: see the module
 * comment for why it cannot be on by default.
 */
export function enableTransitionWhenValidation(): void {
  strictValidation = true;
}

export function isTransitionWhenValidationEnabled(): boolean {
  return strictValidation;
}

/** @internal Reset for unit tests. */
export function resetTransitionWhenValidation(): void {
  strictValidation = false;
}

/** Thrown for an invalid transition({ when }); recognized by the dev HMR overlay. */
export class TransitionWhenError extends Error {
  override readonly name: string = "TransitionWhenError";
}

/**
 * The TransitionWhenError in an error's cause chain, matched by name: discovery
 * throws it from the module runner's copy of this module (another class
 * object), and include resolution wraps it (build/generate-manifest.ts).
 */
export function findTransitionWhenError(error: unknown): Error | undefined {
  const seen = new Set<unknown>();
  let current: unknown = error;
  while (
    typeof current === "object" &&
    current !== null &&
    !seen.has(current)
  ) {
    seen.add(current);
    if ((current as Error).name === "TransitionWhenError") {
      return current as Error;
    }
    current = (current as { cause?: unknown }).cause;
  }
  return undefined;
}

/** Where an invalid `when` was declared, for the error message. */
export interface TransitionWhenSite {
  /** The route the entry belongs to (the matched or enumerated route). */
  readonly routeName?: string;
  readonly pattern?: string;
  /** The declaring entry's type when it is not the route itself. */
  readonly entryType?: string;
}

function describeSite(site: TransitionWhenSite): string {
  const named =
    site.routeName && !isAutoGeneratedRouteName(site.routeName)
      ? `route "${site.routeName}"${site.pattern ? ` (${site.pattern})` : ""}`
      : site.pattern
        ? `route ${site.pattern}`
        : "a route";
  if (!site.entryType || site.entryType === "route") return named;
  return `a ${site.entryType} of ${named}`;
}

function describeValue(value: unknown): string {
  if (value === null) return "null";
  if (Array.isArray(value)) return "an array";
  return typeof value;
}

/**
 * The problem with a `when` value, or null when it is valid. Non-functions
 * are always invalid; a plain function is invalid only under strict
 * validation (see the module comment).
 */
export function transitionWhenProblem(
  when: unknown,
  strict: boolean,
): "not-a-function" | "server-function" | null {
  if (when === undefined || isClientUrlsWhenRef(when)) return null;
  if (typeof when !== "function") return "not-a-function";
  if (strict && !isClientReference(when)) return "server-function";
  return null;
}

export function createTransitionWhenError(
  when: unknown,
  problem: "not-a-function" | "server-function",
  site: TransitionWhenSite,
): TransitionWhenError {
  const where = `transition({ when }) on ${describeSite(site)}`;
  const head =
    problem === "not-a-function"
      ? `${where} must be a function, got ${describeValue(when)}.`
      : `${where} is not a client function.`;
  return new TransitionWhenError(
    `[rango] ${head} ` +
      "`when` runs in the browser: write it inline in the transition() call " +
      "(transition({ when: (ctx) => ... }), where transition is the urls() helper " +
      'or imported from "@rangojs/router"; the build hoists that literal into a ' +
      'client module) or export it from a "use client" module and import it ' +
      "into your urls() file. It receives { kind, from, to, isAction, action }: " +
      "URLs, params, route names, history state and action data; get(), env " +
      'and handler state do not exist there. See skills/view-transitions "Conditional transitions".',
  );
}

/**
 * Definition-time shape check (the DSL's transition()). Runs in every
 * environment, so it rejects only what is invalid everywhere: a non-function.
 */
export function assertTransitionWhenShape(when: unknown): void {
  if (transitionWhenProblem(when, false) === "not-a-function") {
    throw new TypeError(
      createTransitionWhenError(when, "not-a-function", {}).message,
    );
  }
}

/**
 * Browser: turn a transition config's `when` into the predicate to call.
 * Undefined when there is none (or a clientUrls route no longer declares it).
 */
export function resolveTransitionWhen(
  when: unknown,
): TransitionWhenFn | undefined {
  if (typeof when === "function") return when as TransitionWhenFn;
  if (!isClientUrlsWhenRef(when)) return undefined;
  const definition = when.definition as
    | {
        routes?: ReadonlyArray<{
          id: string;
          transition?: { when?: unknown };
        }>;
      }
    | undefined;
  const record = definition?.routes?.find(
    (candidate) => candidate.id === when.routeId,
  );
  const fn = record?.transition?.when;
  return typeof fn === "function" ? (fn as TransitionWhenFn) : undefined;
}
