// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/about",
  counter: "/counter",
  home: "/",
  prerender: "/prerender",
  "prerender.article": "/prerender/:slug",
  static: "/static",
} as const;

declare global {
  namespace RSCRouter {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
