// Auto-generated by @rangojs/router - do not edit
export const routes = {
  about: "/about",
  counter: "/counter",
  "gallery.1": "/gallery/1",
  "gallery.2": "/gallery/2",
  home: "/",
  prerender: "/prerender",
  "prerender.article": "/prerender/:slug",
  static: "/static",
  "transition.a": "/transition-a",
  "transition.b": "/transition-b",
} as const;
export type routes = typeof routes;
