// Auto-generated by @rangojs/router - do not edit
export const routes = {
  cart: "/cart",
  cartItem: "/cart/:itemId",
  catalog: "/catalog",
  health: "/health",
  product: "/catalog/:productId",
} as const;
export type routes = typeof routes;
