// Auto-generated by @rangojs/router - do not edit
export type routes = {
  "cacheStatus.notFound": "/cache-status/not-found";
  "cacheStatus.redirect": "/cache-status/redirect";
  "cacheStatus.redirectTarget": "/cache-status/redirect-target";
  "cacheStatus.serverError": "/cache-status/server-error";
  "cacheStatus.success": "/cache-status/success";
  "cacheTest.cachedLoader": "/cache-test/cached-loader";
  "cacheTest.interceptDetail": "/cache-test/intercept/:itemId";
  "cacheTest.interceptIndex": "/cache-test/intercept";
  "cacheTest.nonCachedLoader": "/cache-test/non-cached-loader";
  "cacheTest.useLoaderDetail": "/cache-test/useloader/:itemId";
  "cacheTest.useLoaderIndex": "/cache-test/useloader";
  "proactiveCache.index": "/proactive-cache";
  "proactiveCache.itemA": "/proactive-cache/item-a";
  "proactiveCache.itemB": "/proactive-cache/item-b";
};
