// Auto-generated by @rangojs/router - do not edit
export const routes = {
  detail: "/posts/:postId",
  index: "/",
  locale: "/locale/:locale(en|gb)",
  "nested.index": "/nested",
  optional: "/items/:itemId/:section?",
  searchRoute: { path: "/search", search: { q: "string", page: "number?" } },
} as const;
export type routes = typeof routes;
