// Auto-generated by @rangojs/router - do not edit
export type routes = {
  "errors.clientError": "/errors/client-error";
  "errors.index": "/errors";
  "errors.serverError": "/errors/server-error";
  "errors.streamingError": "/errors/streaming-error";
};
