// Auto-generated by @rangojs/router - do not edit
export const routes = {
  "errors.clientError": "/errors/client-error",
  "errors.flakyCache": "/errors/flaky-cache",
  "errors.flakyHeal": "/errors/flaky/heal",
  "errors.flakyPpr": "/errors/flaky-ppr",
  "errors.flakyReset": "/errors/flaky/reset",
  "errors.index": "/errors",
  "errors.renderingError": "/errors/rendering-error",
  "errors.serverError": "/errors/server-error",
  "errors.slotAncestor": "/errors/slot-ancestor",
  "errors.streamingDeclared": "/errors/streaming-declared",
  "errors.streamingDeclaredNoSsr": "/errors/streaming-declared-no-ssr",
  "errors.streamingError": "/errors/streaming-error",
  "errors.streamingNotFound": "/errors/streaming-not-found",
} as const;
export type routes = typeof routes;
