// Auto-generated by @rangojs/router - do not edit
export const routes = {
  "errors.clientError": "/errors/client-error",
  "errors.index": "/errors",
  "errors.serverError": "/errors/server-error",
  "errors.streamingError": "/errors/streaming-error",
} as const;
export type routes = typeof routes;
