// Auto-generated by @rangojs/router - do not edit
export const routes = {
  fetchLoader: "/fetch-loader",
  "hookTests.formAction": "/hook-tests/form-action",
  "hookTests.index": "/hook-tests",
  "hookTests.noLoader": "/hook-tests/no-loader",
  "hookTests.routeA": "/hook-tests/route-a",
  "hookTests.routeB": "/hook-tests/route-b",
  "hookTests.useRouter": "/hook-tests/use-router",
  "hookTests.useRouterTargetA": "/hook-tests/use-router/target-a",
  "hookTests.useRouterTargetB": "/hook-tests/use-router/target-b",
  inlineAction: "/inline-action",
  loaderComposition: "/loader-composition",
  progressiveEnhancement: "/progressive-enhancement",
} as const;
export type routes = typeof routes;
