// Auto-generated by @rangojs/router - do not edit
export type routes = {
  fetchLoader: "/fetch-loader";
  "hookTests.formAction": "/hook-tests/form-action";
  "hookTests.index": "/hook-tests";
  "hookTests.noLoader": "/hook-tests/no-loader";
  "hookTests.routeA": "/hook-tests/route-a";
  "hookTests.routeB": "/hook-tests/route-b";
  inlineAction: "/inline-action";
  loaderComposition: "/loader-composition";
  progressiveEnhancement: "/progressive-enhancement";
};
