// Auto-generated by @rangojs/router - do not edit
export const routes = {
  detail: "/:id",
  filtered: { path: "/filtered/:category", search: { q: "string", page: "number?", active: "boolean?" } },
  index: "/",
  "nested.index": "/nested",
} as const;
export type routes = typeof routes;
