// Auto-generated by @rangojs/router - do not edit
export const routes = {
  absolute: "/absolute",
  child: "/child",
  deep: "/deep/nested",
  handlePassthrough: "/handle-passthrough",
  handlePassthroughAsync: "/handle-passthrough-async",
  hydrationTest: "/hydration-test",
  index: "/",
  nested: "/nested",
  nestedChild: "/nested/child",
  "trailingSlash.always": "/ts-always",
  "trailingSlash.ignore": "/ts-ignore",
  "trailingSlash.never": "/ts-never",
  unsetThenSet: "/unset-then-set",
} as const;
export type routes = typeof routes;
