// Auto-generated by @rangojs/router - do not edit
export type routes = {
  cookies: "/cookies";
  errorHandler: "/error-handler/trigger";
  index: "/";
  params: "/params/:paramId";
  protectedDashboard: "/protected/dashboard";
  routeLevel: "/route-level";
  routeLevelWithParams: "/route-level/:routeId";
  sharedVars: "/shared-vars";
};
