// Auto-generated by @rangojs/router - do not edit
export const routes = {
  changelog: "/changelog",
  docs: "/docs",
  "docs.article": "/docs/:slug",
} as const;
export type routes = typeof routes;
