// Auto-generated by @rangojs/router - do not edit
export const routes = {
  bothProps: "/both-props",
  handleProp: "/handle-prop",
  loaderProp: "/loader-prop",
} as const;
export type routes = typeof routes;
