// Auto-generated by @rangojs/router - do not edit
export const routes = {
  detail: { path: "/:category", search: { q: "string?", active: "boolean?" } },
  index: { path: "/", search: { q: "string", page: "number?", sort: "string?" } },
} as const;
export type routes = typeof routes;
