// Auto-generated by @rangojs/router - do not edit
export const routes = {
  docCache: "/doc-cache",
  docCacheLive: "/doc-cache/live",
  index: "/",
  ppr: "/ppr",
  pprClient: "/ppr-client",
  pprRc: "/ppr-rc",
  toggle: "/toggle",
} as const;
export type routes = typeof routes;
