// Auto-generated by @rangojs/router - do not edit
export const routes = {
  health: "/health",
  item: "/items/:id",
  items: "/items",
  stats: "/stats",
} as const;
export type routes = typeof routes;
