// Auto-generated by @rangojs/router - do not edit
export const routes = {
  benchFirst: "/bench/first",
  benchLast: "/bench/last",
  home: "/",
  links: "/links",
  reverseTest: "/reverse-test",
} as const;
export type routes = typeof routes;
