// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/about",
  cached: "/cached",
  home: "/",
} as const;

// Aliased so the augmentation below does not pay a homomorphic mapped-type
// instantiation per route; `as const` already makes the members readonly.
type NamedRoutesShape = typeof NamedRoutes;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends NamedRoutesShape {}
  }
}
