// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/about",
  cached: "/cached",
  home: "/",
} as const;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
