/**
 * Test-only recording tracer for the Vercel custom-spans e2e.
 *
 * Real Vercel OTel spans only surface in Vercel's trace waterfall / a Trace
 * Drain, which an e2e cannot read. Unlike Cloudflare — where you own the worker
 * entry and can wrap the response to attach a header — the Vercel function entry
 * is generated by the preset, so the consumer cannot wrap it. We expose spans
 * through the router instead: in the debug build (`RANGO_TRACE_DEBUG=1`) this
 * recorder is wired as `createVercelTracing({ tracer })`, captures the `rango.*`
 * span tree per request (nesting by async context via AsyncLocalStorage), and a
 * `/__debug/trace` route returns the most recent tree for the e2e to assert
 * against. The router code under test is identical to production; only the
 * tracer stands in for the platform's OpenTelemetry SDK.
 *
 * It captures each span's name and attributes and nests by JS async context. It
 * does NOT model span end/duration: the tree is read after the response is
 * constructed, so a streaming phase span may still be "open" — the e2e asserts
 * tree SHAPE only, not lifecycle.
 */

import { AsyncLocalStorage } from "node:async_hooks";

export interface SpanNode {
  name: string;
  attributes: Record<string, string | number | boolean>;
  children: SpanNode[];
}

const als = new AsyncLocalStorage<SpanNode>();
let lastTrace: SpanNode | null = null;

/** The most recently completed root span tree, or null if none recorded. */
export function getLastTrace(): SpanNode | null {
  return lastTrace;
}

interface RecordingSpan {
  setAttribute(key: string, value: string | number | boolean): RecordingSpan;
  setStatus(status: { code: number; message?: string }): RecordingSpan;
  recordException(exception: Error): void;
  end(): void;
}

/**
 * An OpenTelemetry-shaped tracer (the `startActiveSpan` surface
 * `createVercelTracing` bridges onto) that records spans in memory instead of
 * exporting them.
 */
export const recordingTracer = {
  startActiveSpan<T>(name: string, fn: (span: RecordingSpan) => T): T {
    const node: SpanNode = { name, attributes: {}, children: [] };
    const parent = als.getStore();
    if (parent) parent.children.push(node);

    const span: RecordingSpan = {
      setAttribute(key, value) {
        node.attributes[key] = value;
        return span;
      },
      setStatus() {
        return span;
      },
      recordException() {},
      end() {},
    };

    const out = als.run(node, () => fn(span));

    // Root span: publish the completed tree once the work settles. Stored at
    // settle (not creation) so a later request reading getLastTrace() sees the
    // PRIOR request's full tree, not its own just-started root.
    if (!parent) {
      if (out instanceof Promise) {
        return out.finally(() => {
          lastTrace = node;
        }) as T;
      }
      lastTrace = node;
    }
    return out;
  },
};
