// Auto-generated by @rangojs/router - do not edit
export const routes = {
  index: "/",
  settings: "/settings",
  user: "/users/:id",
  users: "/users",
} as const;
export type routes = typeof routes;
