// Auto-generated by @rangojs/router - do not edit
export const routes = {
  clientError: "/client-error",
  "errors.unhandled": "/errors/unhandled",
  index: "/",
  loaderError: "/loader-error",
  notFound: "/not-found",
  notFoundLoader: "/not-found-loader",
  throwError: "/throw",
} as const;
export type routes = typeof routes;
