// Auto-generated by @rangojs/router - do not edit
export const routes = {
  "account.index": "/account",
  "account.orderDetail": "/account/orders/:id",
  "account.orders": "/account/orders",
  cart: "/cart",
  "checkout.confirm": "/checkout/confirm",
  "checkout.index": "/checkout",
  "checkout.payment": "/checkout/payment",
  index: "/",
  "products.category": "/products/:category",
  "products.detail.reviews.detail": "/product/:slug/reviews/:reviewId",
  "products.detail.reviews.edit.index": "/product/:slug/reviews/:reviewId/edit",
  "products.detail.reviews.index": "/product/:slug/reviews",
  "products.detail.view": "/product/:slug",
} as const;
export type routes = typeof routes;
