/**
 * Request Context - AsyncLocalStorage for passing request-scoped data throughout rendering
 *
 * This is the unified context used everywhere:
 * - Middleware execution
 * - Route handlers and loaders
 * - Server components during rendering
 * - Error boundaries and streaming
 *
 * Available via getRequestContext() anywhere in the request lifecycle.
 */

import { AsyncLocalStorage } from "node:async_hooks";
import { parseCookiesFromHeader } from "./cookie-parse.js";
import type { CacheErrorCategory } from "../cache/cache-error.js";
import type { CookieOptions } from "../router/middleware.js";
import {
  KEEP_CACHE_HEADER,
  getRawCookieValue,
  freshReadsCookieName,
  mintStateValue,
  serializeStateCookie,
} from "../browser/cookie-name.js";
import type { LoaderDefinition, LoaderContext } from "../types.js";
import type { ScopedReverseFunction } from "../reverse.js";
import type {
  DefaultEnv,
  DefaultReverseRouteMap,
  DefaultRouteName,
} from "../types/global-namespace.js";
import type { Handle } from "../handle.js";
import {
  type ContextVar,
  contextGet,
  contextSet,
  isNonCacheable,
} from "../context-var.js";
import {
  createHandleStore,
  buildHandleSnapshot,
  type HandleStore,
  type HandleData,
} from "./handle-store.js";
import { isHandle } from "../handle.js";
import { withDefer } from "../defer.js";
import { type MetricsStore } from "./context.js";
import { observePhase, PHASES } from "../router/instrument.js";
import { getFetchableLoader } from "./fetchable-loader-store.js";
import type { SegmentCacheStore } from "../cache/types.js";
import type { RouterVersions } from "../router-versions.js";
import type { Theme, ResolvedThemeConfig } from "../theme/types.js";
import type { ExecutionContext, RequestScope } from "../types/request-scope.js";
import type { TransitionWhenRecord } from "../router/transition-when.js";
import type { ResolvedTracing } from "../router/tracing.js";
import type { RenderMode, RenderPhase } from "../router/timeout.js";
import {
  THEME_COOKIE,
  isValidTheme,
  warnInvalidTheme,
} from "../theme/constants.js";
import type { LocationStateEntry } from "../browser/react/location-state-shared.js";
import type { RoutineTrace } from "../rsc/routine-plan.js";
import { NOCACHE_SYMBOL, assertNotInsideCacheExec } from "../cache/taint.js";
import {
  assertCachedHeaderWriteAllowed,
  assertNonCacheableReadAllowed,
  clearPprHeaderScope,
  runInsideLoaderRun,
  type LoaderRunIdentity,
} from "./context.js";
import { readStartedLoaderValue, trackLoaderRun } from "../cache/cache-tag.js";
import {
  guardRawCookieRead,
  guardRequestHeaders,
  readGuardedTheme,
} from "./cookie-store.js";
import { requestHeaders } from "./request-headers.js";
import {
  createReverseFunction,
  stripInternalParams,
} from "../router/handler-context.js";
import {
  getGlobalRouteMap,
  isRouteRootScoped,
  getSearchSchema,
} from "../route-map-builder.js";
import { parseSearchParams } from "../search-params.js";
import {
  executionStart,
  type ExecutionStart,
} from "../cache/invalidation-order.js";
import { invariant } from "../errors.js";
import { isAutoGeneratedRouteName } from "../route-name.js";

export interface RenderForegroundCursor {
  mode: RenderMode;
  phase: RenderPhase;
  state: "paused" | "running";
  completed: number;
  total: number;
  pipelineStartedAt: number;
  phaseStartedAt?: number;
  routeKey?: string;
  actionId?: string;
}

/**
 * Unified request context available via getRequestContext()
 *
 * This is the same context passed to middleware and handlers.
 * Use this when you need access to request data outside of route handlers.
 */
export interface RequestContext<
  TEnv = DefaultEnv,
  TParams = Record<string, string>,
> extends RequestScope<TEnv> {
  /** @internal Shared variable backing store for ctx.get()/ctx.set(). */
  _variables: Record<string, any>;
  /** Get a variable set by middleware */
  get: {
    <T>(contextVar: ContextVar<T>): T | undefined;
    <K extends string>(key: K): any;
  };
  /** Set a variable (shared with middleware and handlers) */
  set: {
    <T>(
      contextVar: ContextVar<T>,
      value: T,
      options?: { cache?: boolean },
    ): void;
    <K extends string>(key: K, value: any, options?: { cache?: boolean }): void;
  };
  /**
   * Route params (populated after route matching)
   * Initially empty, then set to matched params
   */
  params: TParams;
  /** @internal Stub response for collecting headers/cookies. Use ctx.headers or ctx.header() instead. */
  readonly res: Response;

  /**
   * True for build-time render/capture requests. Live requests use false.
   * Build-time shell capture sets this while replaying middleware so apps can
   * skip side-effectful runtime work.
   */
  readonly build: boolean;

  /**
   * Opt this request out of PPR shell serving/capture.
   * Runtime middleware can call this before the PPR commit point; handlers can
   * call it on a MISS to prevent the follow-up capture.
   *
   * Scope: the PPR SHELL axis only. It does NOT disable prerender B-segment
   * (Prerender/Static) serving, and it is inert in the prerender-collect /
   * static-render contexts (no live shell decision to influence there).
   */
  dynamic(): void;

  /** @internal Request-local PPR opt-out marker set by ctx.dynamic(). */
  _dynamic?: boolean;

  /**
   * @internal Get a cookie value (effective: request + response mutations).
   * Use cookies().get() instead. Guarded like cookies() (#976).
   */
  cookie(name: string): string | undefined;
  /**
   * @internal Get all cookies (effective merged view). Use
   * cookies().getAll() instead. Guarded like cookies() (#976).
   */
  cookies(): Record<string, string>;
  /**
   * @internal `cookie()` without the identity guard: the read behind the
   * cookies() store, which guards at its own call and records per read
   * method. Non-enumerable, like `_readTheme`.
   */
  _readCookie(name: string): string | undefined;
  /** @internal `cookies()` without the identity guard (see `_readCookie`). */
  _readCookies(): Record<string, string>;
  /** @internal Set a cookie on the response. Use cookies().set() instead. */
  setCookie(name: string, value: string, options?: CookieOptions): void;
  /** @internal Delete a cookie. Use cookies().delete() instead. */
  deleteCookie(
    name: string,
    options?: Pick<CookieOptions, "domain" | "path">,
  ): void;
  /** Set a response header */
  header(name: string, value: string): void;
  /** Set the response status code */
  setStatus(status: number): void;
  /** @internal Set status bypassing cache-exec guard (for framework error handling) */
  _setStatus(status: number): void;
  /** @internal Rotate the rango state cookie (server seat of invalidateClientCache). */
  _rotateStateCookie(): void;
  /** @internal Set the keepClientCache() directive header on the response. */
  _setKeepCacheDirective(): void;
  /**
   * @internal This request carries the fresh-reads cookie: it follows an
   * updateTag()/revalidateTag() by the same user, so the stores read tag
   * markers and shells from the store, not from an isolate memo.
   */
  _freshReads?: boolean;
  /**
   * @internal Set the fresh-reads cookie on this response for `maxAgeMs`
   * (rounded up to whole seconds; the longest stays). Called by
   * updateTag()/revalidateTag().
   */
  _setFreshReadsCookie(maxAgeMs: number): void;
  /**
   * @internal The context createRequestContext() returned. A context derived
   * from it with Object.create (a PPR HIT tail, a shell capture, a background
   * revalidation render) inherits it, so per-request invalidation state (the
   * stores' masks) is keyed by the request, not by whichever derived object
   * called or read (#973).
   */
  _requestRoot?: RequestContext<any, any>;
  /**
   * @internal Where the request started in the isolate's invalidation order
   * (cache/invalidation-order.ts), taken when createRequestContext() ran. The
   * document cache gates its write on it (#977): a middleware ahead of the
   * document cache can read tagged data the document bakes.
   */
  _requestStart?: ExecutionStart;
  /**
   * @internal The handler has handed the response to the host (rsc/handler.ts
   * `rango.response`): header and cookie writes after this are lost, as from
   * a streaming loader or render.
   */
  _responseSent?: boolean;

  /**
   * Access loader data or push handle data.
   *
   * For loaders: Returns a promise that resolves to the loader data.
   * Loaders are executed in parallel and memoized per request.
   *
   * For handles: Returns a push function to add data for this segment.
   * Handle data accumulates across all matched route segments.
   *
   * @example
   * ```typescript
   * // Loader usage
   * const cart = await ctx.use(CartLoader);
   *
   * // Handle usage
   * const push = ctx.use(Breadcrumbs);
   * push({ label: "Shop", href: "/shop" });
   * ```
   */
  use: {
    <T, TLoaderParams = any>(
      loader: LoaderDefinition<T, TLoaderParams>,
    ): Promise<T>;
    <TData, TAccumulated = TData[]>(
      handle: Handle<TData, TAccumulated>,
    ): (data: TData | Promise<TData> | (() => Promise<TData>)) => void;
  };

  /** HTTP method (GET, POST, PUT, PATCH, DELETE, etc.) */
  method: string;

  /**
   * @internal Handle store for tracking handle data across segments.
   * Readonly: a background render that needs its own store derives a context
   * (rerenderAndCacheRoute, shell-capture.ts) instead of swapping this field,
   * which the foreground still reads while it produces the page.
   */
  readonly _handleStore: HandleStore;

  /**
   * @internal transition({ when }) client references of the matched entry
   * chain, keyed by segment id. Recorded at match time from the static route
   * definition (router/transition-when.ts) and attached to the payload's
   * segments right before Flight (rsc/attach-transition-when.ts). The server
   * never calls them, and no cache or snapshot stores them.
   */
  _transitionWhenRefs?: ReadonlyMap<string, TransitionWhenRecord>;

  /**
   * @internal Post-match serve-source truth for the PPR replay reporter.
   * Stamped from the match context as `intercept`, then overwritten as
   * `prerender-store` if that lookup actually serves. The latter wins because
   * it identifies the response source. matchPartialWithPprReplay reads this
   * AFTER matching to reclassify its pre-match guess and suppress pointless
   * heal captures.
   */
  _pprReplayPostMatchReason?: "prerender-store" | "intercept";

  /** @internal Cache store for segment caching (optional, used by CacheScope) */
  _cacheStore?: SegmentCacheStore;

  /**
   * @internal Compiled `cache.searchParams` filter for default cache-key
   * generation (undefined = "all", the byte-stable unfiltered format). Set
   * once per request by handler.ts; every URL-keyed tier (segment, document,
   * response, shell, "use cache") reads it so the tiers cannot drift.
   */
  _searchParamsFilter?: import("../cache/search-params-filter.js").SearchParamsFilter;

  /**
   * @internal PPR shell-capture ACTIVE marker. True ONLY inside the background
   * capture task's derived request context (built by shell-capture.ts). This is
   * the switch every capture-specific behavior reads: loader masking
   * (loader-mask.ts isShellCaptureActive / fresh.ts emitStreaming) and the
   * identity-read capture guard (server/context.ts guardIdentityRead). The
   * foreground render never sets it, so the
   * served response is byte-identical to axis 1. The capture descriptor itself
   * (key/ttl/swr/tags/store) is NOT threaded through the request context — the
   * integrated PPR serve path (rsc/shell-serve.ts + rsc-rendering.ts) builds it
   * locally and passes it to scheduleShellCapture directly.
   */
  _shellCaptureRun?: boolean;

  /**
   * @internal Bake-lane loader containers collected DURING a shell capture:
   * segment-key -> the loader's (pre-wrap) result promise. Populated by
   * resolveLoaderData for bake-lane loaders (lane rule: see its JSDoc in
   * loader-cache.ts). Drained by captureAndStoreShell after the shell
   * quiesces: settled containers are promise-elided, Flight-serialized, and
   * pinned into the snapshot's loader family; a REJECTED container refuses
   * the capture (error UI must never bake into the shared shell). Own
   * property of the capture's derived context only.
   */
  _shellCaptureLoaderRecords?: Map<string, Promise<unknown>>;

  /**
   * @internal Set on a capture's derived context when a loader pushed a
   * value the record cannot keep (a deferred push, masked nested promises,
   * or a push outside a loader body): the loader records then carry
   * `runs: 1`, so a HIT still runs their bodies for those pushes.
   */
  _shellCaptureUnrecordedLoaderPush?: true;

  /**
   * @internal The lane of each loader the capture's matched route registers
   * (loader-cache.ts routeLoaderLanes), set by createMatchContextForFull
   * before any loader runs. The capture's push funnel credits a push made
   * under a live-lane loader's body, at any depth, to that loader
   * (shell-capture.ts deriveShellCaptureContext). Own property of the
   * capture's derived context only.
   */
  _shellCaptureLoaderLanes?: ReadonlyMap<string, "live" | "bake">;

  /**
   * @internal Record keys resolved for this request (CacheScope
   * resolveKeyFrom): by the scope's `key()` (one result) or its store's
   * keyGenerator (one per default key). A shell capture's derived context
   * reads it through the prototype chain, so the capture reuses the
   * partition its request resolved instead of running `key()` again.
   */
  _resolvedCacheKeys?: Map<unknown, Map<string, Promise<string>>>;

  /**
   * @internal The shell store key the PPR serve path resolved for this
   * document request (rsc-rendering.ts shellServePlan), request partition
   * included. Read by the testing helper serveShellRequest.
   */
  _shellKey?: string;

  /**
   * @internal The request carried the forced-MISS reload marker
   * (shell-serve.ts SHELL_MISS_PARAM). The handler strips the marker from the
   * request on entry and sets this; the shell gate renders the request like a
   * cache miss.
   */
  _shellForcedMiss?: true;

  /**
   * @internal The freshness window of the route cache() records this
   * request read or wrote (cache-scope.ts noteRouteRecordWindow), as ms
   * timestamps: `freshUntil` is the record's `expiresAt`, `staleUntil` adds
   * its scope's swr. The narrowest record wins. A shell capture caps its
   * entry's ttl and ttl+swr to it (shell-capture.ts capShellWindow), so a
   * shell is never fresher, or served longer, than the route cache() entry
   * it replayed or wrote.
   */
  _routeRecordWindow?: RouteRecordWindow;

  /**
   * @internal Loader-family snapshot seed for a shell HIT's tail render:
   * segment-key -> the capture's elided container (already Flight-deserialized
   * by serveShellHit) plus its capture-computed hole bit. resolveLoaderData
   * overlays it onto the fresh run's container (recorded paths pinned,
   * hole-marker paths keep the fresh nested promises) so the payload's baked
   * bytes match the frozen prelude; a hole-free entry resolves pin-first
   * and does not run the loader. Two owners: serveShellHit sets it on the
   * HIT tail's derived context, and matchPartialWithPprReplay sets it on the
   * request context of a PPR partial replay once its doc record hits, and
   * restores the previous value after the match.
   */
  _shellLoaderSeed?: Map<
    string,
    import("../cache/shell-snapshot.js").ShellLoaderSeedEntry
  >;

  /**
   * @internal The doc record marker: makes the next match treat the whole
   * matched route as an implicit doc-level cache() boundary (see
   * resolveShellImplicitCacheScope in cache/cache-scope.ts). Set ONLY on
   * (a) the capture's derived context — with a record-only store so the
   * capture's cacheRoute write lands in the snapshot, never the real store —
   * (b) a document HIT tail's seeded context (`docTail`), and (c) an eligible
   * normal-route partial replay, where `store` is a request-local segment
   * overlay.
   * A document HIT tail replays the record even for a route with its own
   * cache() config (the gate before the commit already evaluated that
   * scope's opt-outs). Elsewhere the route's scope stays authoritative. On the
   * navigation-replay serve path (`onExplicitHit` set) the marker COMPOSES with
   * such a scope instead of being ignored: the seeded doc record supplies the match
   * only when the explicit tier misses (withCacheLookup). cache(false) and a
   * false condition() stay absolute opt-outs — replay bypasses before any
   * shell read (`cache-disabled`).
   */
  _shellImplicitCache?: {
    ttl?: number;
    swr?: number;
    store?: SegmentCacheStore;
    /**
     * @internal Override the implicit scope's default cache namespace. Shell
     * captures and navigation replay both consume the canonical document
     * segment record even when the triggering request is partial.
     */
    keyPrefix?: "doc";
    /**
     * @internal Called only after the implicit cache hit decodes
     * successfully; the lookup awaits it before returning the hit, so work
     * it starts lands before the route's loaders resolve.
     */
    onHit?: () => void | Promise<void>;
    /**
     * @internal Called when the seeded document record fails server-side
     * deserialization. Partial replay uses it to replace the enclosing shell
     * snapshot after serving the fresh fallback. A document HIT tail does not
     * set it: withCacheLookup throws ShellRecordUnavailableError instead.
     */
    onCorrupt?: () => void;
    /**
     * @internal The resolved key of the canonical document segment record.
     * Written during a CAPTURE render by CacheScope.cacheRoute when a
     * doc-namespaced scope records the matched segments; captureAndStoreShell
     * stamps it onto the ShellCacheEntry (`docKey`) so replay eligibility can
     * require the exact consumable record instead of "any segment record".
     */
    docKey?: string;
    /**
     * @internal Set on a document HIT tail (serveShellHit). The implicit doc
     * scope replaces any route-derived cache() scope for the tail's match
     * (resolveShellImplicitCacheScope), and a lookup that does not hit throws
     * ShellRecordUnavailableError instead of resolving segments
     * (withCacheLookup): a HIT never runs a handler. The record's
     * loader-owned handle pushes restore as authoritative
     * (HandleStore.pushRestored): the prelude rendered them.
     */
    docTail?: true;
    /**
     * @internal The key a document HIT tail looks the doc record up by: the
     * entry's own `docKey`. Recomputing it could name another key (a store
     * keyGenerator folding request data, a build-time capture's synthetic
     * host) and miss the record.
     */
    fixedDocKey?: string;
    /**
     * @internal Set ONLY by matchPartialWithPprReplay on the navigation-replay
     * serve path. Its presence arms the explicit-scope composition in
     * withCacheLookup: a route-derived cache() scope stays authoritative, and
     * only when its lookup MISSes does the seeded doc record supply the match.
     * A capture render must never set this (its match must re-run handlers so
     * SWR recapture stays fresh), which is why the fallback keys off this
     * field and not off the marker itself. Fired when the route-derived
     * scope's own lookup supplied the match — the header then reports
     * `BYPASS; reason=explicit-cache-hit`, never a false replay HIT.
     */
    onExplicitHit?: () => void;
    /**
     * @internal Companion to onExplicitHit, same lifecycle: fired when the
     * route-derived scope's lookup REFUSED the read (`bypass` outcome — a
     * false condition() or no store). The gate only pre-decides the static
     * cache(false) case; a predicate refusal is known only at lookup time and
     * reports `BYPASS; reason=cache-disabled` post-match.
     */
    onExplicitBypass?: () => void;
  };

  /**
   * @internal Fragment-passthrough marker: cache/prerender-store hits during
   * THIS render emit stored segment fragments VERBATIM into the payload
   * (segment-codec fragmentSegments) instead of deserialize -> re-serialize
   * per request; the payload consumers (SSR resume, browser hydration, and
   * the client partial-navigation decode chokepoints) expand them
   * (segment-fragments.ts, issue #700). Partial requests arm only after the
   * browser advertises `X-Rango-Fragment-Passthrough: 1`; a decode failure
   * retries without it so CacheScope can evict the bad record. Two arming sites,
   * both scoped to a
   * render/match window: serveShellHit's derived tail context (document
   * HIT), and matchPartialWithPprReplay's mutate-restore around the partial
   * match (matchPartialForReplay). It must never be visible to a capture
   * render: the capture SSR-prerenders the payload AND serializes segments
   * into records (cacheRoute), and an envelope reaching serializeSegments
   * would store a double-encoded fragment — deriveShellCaptureContext resets
   * it as an own property for exactly that reason.
   */
  _shellFragmentPayload?: boolean;

  /**
   * @internal Set by the capture guard (server/context.ts
   * guardIdentityRead) when it throws DURING a capture render: the read
   * ("cookies()", "headers()", `ctx.get() for a non-cacheable variable`,
   * "ctx.theme") and the fix the
   * refusal warning gives for it. Load-bearing for the
   * bake lane: a guard throw inside an executing loader is swallowed by
   * wrapLoaderPromise into per-loader error UI, which would otherwise bake
   * silently into the shared shell — the capture checks this flag after the
   * render and refuses instead. Deterministic, so the capture does not retry.
   */
  _shellCaptureGuardTripped?: { surface: string; fix: string };

  /**
   * @internal The loader $$id whose BODY was executing when the capture guard
   * tripped (read off the loader-body ALS scope at trip time), or undefined
   * when the read came from handler/render code. Only used to make the
   * once-per-key refusal warning name the real source — the old text
   * hardcoded "a bake-lane loader", which misattributed handler-land reads
   * and sent users debugging the wrong lane (issue #672, secondary).
   */
  _shellCaptureGuardTrippedLoaderId?: string;

  /**
   * @internal Handler-owned registry of explicit per-scope stores from
   * cache({ store }). Created once per createRSCHandler() and threaded into
   * every request context, so it accumulates every explicit store the handler
   * resolves. updateTag()/revalidateTag() iterate this set plus _cacheStore to
   * reach every store that may hold tagged entries. The app-level store is not
   * added here (it is always reachable via _cacheStore).
   */
  _explicitTaggedStores?: Set<SegmentCacheStore>;

  /**
   * @internal Union of every cache tag resolved while producing this request's
   * response (from cache({ tags }), runtime cacheTag(), and loader cache tags).
   * Populated at the tag-resolution sites via recordRequestTags(). Read by the
   * document cache middleware so a full-page entry is tagged with everything its
   * content used and can therefore be invalidated by updateTag()/revalidateTag().
   */
  _requestTags: Set<string>;

  /**
   * @internal This request can write a route cache() record: its match
   * resolved a cache scope (match-api.ts). Arms the record tag owners
   * (cache-tag.ts armRecordTagOwners); off, the segment scopes, loader links
   * and owned tag sets are skipped entirely. A capture's or background
   * re-render's derived context (Object.create) inherits it.
   */
  _recordTagOwners?: true;

  /**
   * @internal This request resolves a loader bound with its own cache()
   * (match-api.ts, or the binding's funnel). Arms the per-execution loader
   * tag sets (cache-tag.ts armLoaderTagSets); off, a loader execution
   * allocates no set and a read links nothing. Derived contexts inherit it.
   */
  _recordLoaderTags?: true;

  /** @internal Cache profiles for "use cache" profile resolution (per-router) */
  _cacheProfiles?: Record<
    string,
    import("../cache/profile-registry.js").CacheProfile
  >;

  /**
   * Register a callback to run when the response is created.
   * Callbacks are sync and receive the response. They can:
   * - Inspect response status/headers
   * - Return a modified response
   * - Schedule async work via waitUntil
   *
   * @example
   * ```typescript
   * ctx.onResponse((res) => {
   *   if (res.status === 200) {
   *     ctx.waitUntil(async () => await cacheIt());
   *   }
   *   return res;
   * });
   * ```
   */
  onResponse(callback: (response: Response) => Response): void;

  /** @internal Registered onResponse callbacks */
  _onResponseCallbacks: Array<(response: Response) => Response>;

  /**
   * @internal Promises of the background tasks scheduled via this context's
   * waitUntil (deferred cache writes, revalidations, consumer tasks). The PPR
   * shell capture drains this list BEFORE its match/render as an ORDERING EDGE:
   * every foreground deferred cache write is scheduled here before the capture
   * task is, so settling the list first guarantees the capture's cache reads
   * observe the foreground's generation instead of racing it (see
   * shell-capture.ts). Tasks whose scheduling fn carries
   * UNTRACKED_BACKGROUND_TASK are not tracked (the capture task itself —
   * tracking it would make that drain await its own promise).
   */
  _pendingBackgroundTasks?: Array<Promise<unknown>>;

  /**
   * Current theme setting (only available when theme is enabled in router config)
   *
   * Returns the theme value from the cookie, or the default theme if not set.
   * This is the user's preference ("light", "dark", or "system"), not the resolved value.
   *
   * The visitor's cookie, so it is guarded like `cookies()`: reading it
   * refuses a ppr shell capture and throws inside a `cache()` boundary or a
   * `"use cache"` function (#971). A non-enumerable getter: a spread or
   * `Object.assign` copy of the context does not carry it.
   *
   * @example
   * ```typescript
   * route("settings", (ctx) => {
   *   const currentTheme = ctx.theme; // "light" | "dark" | "system" | undefined
   *   return <SettingsPage theme={currentTheme} />;
   * });
   * ```
   */
  readonly theme?: Theme;

  /**
   * Set the theme (only available when theme is enabled in router config)
   *
   * Sets a cookie with the new theme value. The change takes effect on the next request.
   *
   * @example
   * ```typescript
   * route("settings", (ctx) => {
   *   if (ctx.method === "POST") {
   *     const formData = await ctx.request.formData();
   *     const newTheme = formData.get("theme") as Theme;
   *     ctx.setTheme(newTheme);
   *   }
   *   return <SettingsPage />;
   * });
   * ```
   */
  setTheme?: (theme: Theme) => void;

  /** @internal Theme configuration (null if theme not enabled) */
  _themeConfig?: ResolvedThemeConfig | null;

  /**
   * @internal The theme cookie (or the default) read with no identity guard.
   * The guarded reads (`theme` here, the handler and middleware `ctx.theme`)
   * call it after guardIdentityRead (readGuardedTheme); the router's own payload read goes
   * through payloadInitialTheme (rsc/full-payload.ts), except the unmatched
   * route's 404 (rsc/handler.ts), which is never stored. Undefined without
   * theme config.
   */
  _readTheme(): Theme | undefined;

  /**
   * @internal Set by the document-cache middleware (cache/document-cache.ts)
   * before it runs a render whose response it may store: the MISS and the
   * stale refresh. payloadInitialTheme reads it (#978).
   */
  _documentCacheRender?: boolean;

  /**
   * @internal Set by payloadInitialTheme when the document payload carries
   * the visitor's theme and it differs from the no-cookie default. The
   * document cache does not store that response (#978).
   */
  _payloadVisitorTheme?: boolean;

  /**
   * Attach location state entries to the current response.
   *
   * For partial (SPA) requests, the state is included in the RSC payload
   * metadata and merged into history.pushState on the client. For redirect
   * responses, the state travels through the redirect payload so the target
   * page can read it via useLocationState.
   *
   * Multiple calls accumulate entries.
   *
   * @example
   * ```typescript
   * ctx.setLocationState(Flash({ text: "Item saved!" }));
   * ```
   */
  setLocationState(entries: LocationStateEntry | LocationStateEntry[]): void;

  /** @internal Accumulated location state entries */
  _locationState?: LocationStateEntry[];

  /**
   * The matched route name, if the route has an explicit name.
   * Undefined before route matching or for unnamed routes.
   * Includes the namespace prefix from include() (e.g., "blog.post").
   */
  routeName?: DefaultRouteName;

  /**
   * Generate URLs from route names.
   * Uses the global route map. After route matching, scoped (`.name`) resolution
   * works within the matched include() scope.
   */
  reverse: ScopedReverseFunction<
    Record<string, string>,
    DefaultReverseRouteMap
  >;

  /** @internal Route name from route matching, used for scoped reverse resolution */
  _routeName?: string;

  /** @internal Previous route key (from the navigation source), used for revalidation */
  _prevRouteKey?: string;

  /**
   * @internal True while the post-action revalidation render is running (set by
   * revalidateAfterAction). The "use cache" runtime reads this to prefer
   * freshness over a fast stale response during an action: a stale entry
   * re-executes in the foreground (so the action response reflects the refreshed
   * value) with only the store write deferred, instead of serving stale and
   * revalidating in the background. A plain navigation (flag unset) keeps SWR.
   */
  _inActionRevalidation?: boolean;

  /**
   * @internal Render barrier for experimental `rendered()` API.
   * Resolves when all non-loader segments have settled and handle data
   * is available. Used by DSL loaders that call `ctx.rendered()`.
   */
  _renderBarrier: Promise<void>;

  /**
   * @internal Resolve the render barrier. Accepts resolved segments, filters
   * out loaders, and captures non-loader segment IDs as the handle ordering.
   * Called after segment resolution (fresh) or handle replay (cache/prerender).
   */
  _resolveRenderBarrier: (
    segments: Array<{ type: string; id: string }>,
  ) => void;

  /**
   * @internal Segment order at barrier resolution time, used by loader
   * ctx.use(handle) to collect handle data in correct order.
   */
  _renderBarrierSegmentOrder?: string[];

  /**
   * @internal Set to true when the matched entry tree contains any `loading()`
   * entries (streaming). On a streaming tree rendered() waits for the streaming
   * handlers to settle (via handleStore.settled) before resolving, and the
   * deadlock guard state is kept live until that wait completes.
   */
  _treeHasStreaming?: boolean;

  /**
   * @internal Loader IDs that have called rendered() and are waiting for the
   * barrier. Used to detect deadlocks when a handler tries to await the same
   * loader via ctx.use(Loader).
   */
  _renderBarrierWaiters?: Set<string>;

  /**
   * @internal Loader IDs that handlers have started awaiting via ctx.use().
   * Used for bidirectional deadlock detection: if a loader later calls
   * rendered() and a handler already awaits it, we can detect the deadlock.
   */
  _handlerLoaderDeps?: Set<string>;

  /**
   * @internal Loader IDs ($$id) whose entries carry `awaitBeforeFlush`
   * (loader(Def, { ssr: false })): segment resolution awaits these
   * before returning, so the render barrier cannot resolve until they settle.
   * rendered() checks this set to fail fast — a flagged loader awaiting the
   * barrier is a guaranteed cycle, not a race. Registered by resolveLoaders
   * (fresh.ts) before loader kickoff; only ever populated on document renders
   * (the flag is stamped per-isSSR at DSL evaluation).
   */
  _awaitBeforeFlushLoaderIds?: Set<string>;

  /**
   * @internal Cached HandleData snapshot built at barrier resolution time.
   * Avoids rebuilding the snapshot on every loader ctx.use(handle) call.
   */
  _renderBarrierHandleSnapshot?: HandleData;

  /**
   * @internal The deadlock guard window is closed (no further handler-awaits-
   * loader cycle is possible). For non-streaming trees this is set when the
   * barrier resolves. For streaming trees the window stays open until
   * handleStore.settled — rendered() keeps waiting past the barrier and a
   * loading() handler can still resume and await a still-waiting loader — so it
   * is set only after settled. The guard (loader-resolution `setupLoaderAccess`)
   * reads this instead of `_renderBarrierSegmentOrder` so it does not go blind
   * during the streaming settle wait.
   */
  _renderBarrierGuardClosed?: boolean;

  /** @internal Per-request error dedup set for onError reporting */
  _reportedErrors: WeakSet<object>;

  /**
   * @internal Errors this response's Flight or Fizz render reported through
   * onError: a component that threw does not fail the stream, which completes
   * with an error row or an errored Suspense boundary. Whole-response captures
   * (document-cache.ts, captureAndStoreShell) store nothing while it is
   * non-empty (issue #915). An array so a render under a derived context (the
   * shell HIT tail) pushes into the request's own list through the prototype;
   * deriveShellCaptureContext gives the capture its own.
   */
  _renderErrors?: unknown[];

  /**
   * @internal Report a non-fatal background error through the router's
   * onError callback. Wired by the RSC handler / router during request
   * creation. Cache-runtime and other subsystems call this to surface
   * errors without failing the response. `category` is surfaced to consumers as
   * `metadata.category` on the onError context (phase `cache`).
   */
  _reportBackgroundError?: (
    error: unknown,
    category: CacheErrorCategory,
  ) => void;

  /** @internal Per-request debug performance override (set via ctx.debugPerformance()) */
  _debugPerformance?: boolean;

  /** @internal Request-scoped performance metrics store */
  _metricsStore?: MetricsStore;

  /**
   * @internal Foreground response-construction cursor. It reports only the
   * generator driver's current Flight/HTML/response operation; concurrent
   * loaders and post-commit stream work have separate lifetimes.
   */
  _renderForeground?: RenderForegroundCursor;

  /** @internal Request routine currently executing, used by timeout diagnostics. */
  _activeRoutine?: RoutineTrace;

  /** @internal Keep the render cursor active for timeout support. */
  _renderDiagnosticsEnabled?: boolean;

  /**
   * @internal True request entry timestamp (performance.now() at handler entry).
   * Set once at request-context creation (rsc/handler.ts) so a metrics store
   * created MID-request — ctx.debugPerformance() or the getMetricsStore wrapper —
   * anchors its timeline to the real request start instead of the opt-in moment,
   * keeping phases that began before the opt-in at their true (non-negative) offset.
   */
  _handlerStart?: number;

  /** @internal Resolved platform phase-span tracing for this request (Cloudflare or OTel) */
  _tracing?: ResolvedTracing;

  /** @internal Router basename for this request (used by redirect()) */
  _basename?: string;

  /** @internal Owning router id; scopes the search-schema/root-scope registry
   *  lookups per router (route-map-builder.ts) */
  _routerId?: string;

  /**
   * @internal Cache versions of the router serving this request. The cache
   * factory builds a store per request without knowing the router, so a store
   * reads its key versions from here, lazily, the same way CFCacheStore
   * resolves its base URL (getCacheVersions, server/build-version-table.ts).
   * Unset on a context no router created; a store then uses the build version.
   */
  _versions?: RouterVersions;

  /**
   * @internal RouteSnapshot from classifyRequest, reused by match/matchPartial
   * to avoid a second resolveRoute call. Cleared on HMR invalidation.
   */
  _classifiedRoute?: import("../router/route-snapshot.js").RouteSnapshot;

  /**
   * @internal Classified request mode from classifyRequest, read by the
   * rango.response span tail (rsc/handler.ts) for the rango.response.mode
   * attribute. Unset when middleware short-circuits before core execution.
   */
  _requestMode?: import("../router/request-classification.js").RequestPlan["mode"];

  /**
   * @internal Coarse route-level cache signal for the X-Rango-Cache debug
   * header. Populated by match/matchPartial only when the debug cache signal
   * gate is enabled (debugCacheSignal option or RANGO_TEST_SIGNALS=1). Read by
   * the response-finalization path (createResponseWithMergedHeaders). Undefined
   * when the gate is off, so no header is emitted.
   */
  _cacheSignal?: import("../router/telemetry.js").CacheSegmentSignal[];
}

/**
 * @internal The freshness window of a route cache() record, as ms
 * timestamps: fresh until `freshUntil` (its `expiresAt`), stale until
 * `staleUntil` (plus its scope's swr). `ttl`, `swr` and `written` describe
 * the record that sets `staleUntil`: its cache() config, and whether this
 * request wrote it (cacheRoute) rather than read it.
 */
export interface RouteRecordWindow {
  freshUntil: number;
  staleUntil: number;
  ttl: number;
  swr: number;
  written: boolean;
}

/**
 * Public view of RequestContext, without internal methods and fields.
 *
 * This is the type exported to library consumers. Internal code should
 * use the full RequestContext interface directly.
 */
export type PublicRequestContext<
  TEnv = DefaultEnv,
  TParams = Record<string, string>,
> = Omit<
  RequestContext<TEnv, TParams>,
  | "cookie"
  | "cookies"
  | "_readCookie"
  | "_readCookies"
  | "setCookie"
  | "deleteCookie"
  | "_handleStore"
  | "_transitionWhenRefs"
  | "_pprReplayPostMatchReason"
  | "_cacheStore"
  | "_searchParamsFilter"
  | "_shellCaptureRun"
  | "_shellImplicitCache"
  | "_shellLoaderSeed"
  | "_shellCaptureLoaderRecords"
  | "_shellCaptureUnrecordedLoaderPush"
  | "_shellCaptureLoaderLanes"
  | "_resolvedCacheKeys"
  | "_shellKey"
  | "_shellForcedMiss"
  | "_routeRecordWindow"
  | "_shellFragmentPayload"
  | "_shellCaptureGuardTripped"
  | "_shellCaptureGuardTrippedLoaderId"
  | "_explicitTaggedStores"
  | "_requestTags"
  | "_recordTagOwners"
  | "_recordLoaderTags"
  | "_cacheProfiles"
  | "_onResponseCallbacks"
  | "_pendingBackgroundTasks"
  | "_themeConfig"
  | "_readTheme"
  | "_documentCacheRender"
  | "_payloadVisitorTheme"
  | "_locationState"
  | "_routeName"
  | "_prevRouteKey"
  | "_inActionRevalidation"
  | "_reportedErrors"
  | "_renderErrors"
  | "_renderBarrier"
  | "_resolveRenderBarrier"
  | "_renderBarrierSegmentOrder"
  | "_treeHasStreaming"
  | "_renderBarrierWaiters"
  | "_handlerLoaderDeps"
  | "_awaitBeforeFlushLoaderIds"
  | "_renderBarrierHandleSnapshot"
  | "_renderBarrierGuardClosed"
  | "_reportBackgroundError"
  | "_debugPerformance"
  | "_metricsStore"
  | "_renderForeground"
  | "_activeRoutine"
  | "_renderDiagnosticsEnabled"
  | "_handlerStart"
  | "_tracing"
  | "_basename"
  | "_routerId"
  | "_versions"
  | "_setStatus"
  | "_rotateStateCookie"
  | "_setKeepCacheDirective"
  | "_freshReads"
  | "_setFreshReadsCookie"
  | "_requestRoot"
  | "_requestStart"
  | "_responseSent"
  | "_variables"
  | "_classifiedRoute"
  | "_requestMode"
  | "_cacheSignal"
  | "_dynamic"
  | "res"
>;

/**
 * Marker for a waitUntil-scheduled fn whose task promise must NOT enter
 * _pendingBackgroundTasks. Used by the PPR shell capture for its own task:
 * the capture's pre-render write barrier settles that list, so tracking the
 * capture itself would make the drain wait on its own (still-running) promise.
 * @internal
 */
export const UNTRACKED_BACKGROUND_TASK: unique symbol = Symbol.for(
  "rango.untrackedBackgroundTask",
);

// AsyncLocalStorage instance for request context
const requestContextStorage = new AsyncLocalStorage<RequestContext<any>>();

/**
 * Run a function within a request context
 * Used by the RSC handler to provide context to server actions
 */
export function runWithRequestContext<TEnv, T>(
  context: RequestContext<TEnv>,
  fn: () => T,
): T {
  return requestContextStorage.run(context, fn);
}

/**
 * Get the current request context
 * Throws if called outside of a request context
 */
export function getRequestContext<TEnv = DefaultEnv>(): RequestContext<TEnv> {
  const ctx = requestContextStorage.getStore() as
    | RequestContext<TEnv>
    | undefined;
  invariant(
    ctx,
    "getRequestContext() called outside of a request context. " +
      "This function must be called from within a route handler, loader, middleware, " +
      "server action, or server component.",
  );
  return ctx;
}

/**
 * @internal Get the request context without throwing — for internal code that
 * may run outside a request context (cache stores, optional handle lookups, etc.)
 */
export function _getRequestContext<TEnv = DefaultEnv>():
  | RequestContext<TEnv>
  | undefined {
  return requestContextStorage.getStore() as RequestContext<TEnv> | undefined;
}

/**
 * Update params on the current request context
 * Called after route matching to populate route params and route name
 */
export function setRequestContextParams(
  params: Record<string, string>,
  routeName?: string,
  routeMap?: Record<string, string>,
): void {
  const ctx = requestContextStorage.getStore();
  if (ctx) {
    ctx.params = params;
    if (routeName !== undefined) {
      ctx._routeName = routeName;
      ctx.routeName = (
        routeName && !isAutoGeneratedRouteName(routeName)
          ? routeName
          : undefined
      ) as DefaultRouteName | undefined;
    }
    // Update reverse with scoped resolution now that route is known. Production
    // omits routeMap and uses the global map (routes are registered globally);
    // the testing primitives (renderToFlightString/renderServerTree) pass a
    // scoped routeMap so `ctx.reverse` is not order-dependent on whatever router
    // registered last.
    ctx.reverse = createReverseFunction(
      routeMap ?? getGlobalRouteMap(),
      routeName,
      params,
      routeName ? isRouteRootScoped(routeName, ctx._routerId) : undefined,
    );
  }
}

/**
 * Store the previous route key on the request context.
 * Called during partial-match context creation to make the navigation source
 * route key available for revalidation and intercept evaluation.
 * @internal
 */
export function setRequestContextPrevRouteKey(
  prevRouteKey: string | undefined,
): void {
  const ctx = requestContextStorage.getStore();
  if (!ctx) return;
  if (prevRouteKey !== undefined) ctx._prevRouteKey = prevRouteKey;
}

/**
 * Get accumulated location state entries from the current request context.
 * Returns undefined if no state has been set.
 *
 * @internal Used by the RSC handler to include state in payload metadata.
 */
export function getLocationState(): LocationStateEntry[] | undefined {
  const ctx = getRequestContext();
  return ctx?._locationState;
}

export type { ExecutionContext };

/**
 * Options for creating a request context
 */
export interface CreateRequestContextOptions<TEnv> {
  env: TEnv;
  request: Request;
  url: URL;
  variables: Record<string, any>;
  /** Optional initial response stub headers/status to seed effective cookie reads */
  initialResponse?: Response;
  /** Optional cache store for segment caching (used by CacheScope) */
  cacheStore?: SegmentCacheStore;
  /**
   * Compiled `cache.searchParams` filter from the resolved handler cache
   * config (handler.ts). Stored as _searchParamsFilter.
   */
  searchParamsFilter?: import("../cache/search-params-filter.js").SearchParamsFilter;
  /**
   * Handler-owned registry of explicit per-scope stores for cross-store tag
   * invalidation. Created once per handler, reused across requests.
   */
  explicitTaggedStores?: Set<SegmentCacheStore>;
  /** Optional cache profiles for "use cache" resolution (per-router) */
  cacheProfiles?: Record<
    string,
    import("../cache/profile-registry.js").CacheProfile
  >;
  /** Optional Cloudflare execution context for waitUntil support */
  executionContext?: ExecutionContext;
  /** Build-time render/capture request marker. Defaults to false. */
  build?: boolean;
  /** Optional theme configuration (enables ctx.theme and ctx.setTheme) */
  themeConfig?: ResolvedThemeConfig | null;
  /** Resolved rango state cookie name, for the server seat of invalidateClientCache(). */
  stateCookieName?: string;
  /**
   * The versions of the router serving this request (resolveRouterVersions).
   * Stored as `_versions` for the cache stores; `document` is also the prefix
   * of a server-rotated rango state value, which the browser compares with the
   * payload's `metadata.version`.
   */
  versions?: RouterVersions;
}

/**
 * Create a full request context with all methods implemented
 *
 * This is used by the RSC handler to create the unified context that's:
 * - Available via getRequestContext() throughout the request
 * - Passed to middleware as ctx
 * - Passed to handlers as ctx
 */
export function createRequestContext<TEnv>(
  options: CreateRequestContextOptions<TEnv>,
): RequestContext<TEnv> {
  const {
    env,
    request,
    url,
    variables,
    initialResponse,
    cacheStore,
    searchParamsFilter,
    explicitTaggedStores,
    cacheProfiles,
    executionContext,
    build = false,
    themeConfig,
    stateCookieName,
    versions,
  } = options;
  // ctx.request.headers is guarded like headers() (#976); every router read
  // of this request's headers goes through requestHeaders().
  guardRequestHeaders(request);
  const cookieHeader = requestHeaders(request).get("Cookie");
  let rangoStateRotated = false;
  const freshCookie = stateCookieName
    ? freshReadsCookieName(stateCookieName)
    : undefined;
  let freshCookieMaxAge = 0;
  let parsedCookies: Record<string, string> | null = null;

  let stubResponse = initialResponse
    ? new Response(null, {
        status: initialResponse.status,
        statusText: initialResponse.statusText,
        headers: new Headers(initialResponse.headers),
      })
    : new Response(null, { status: 200 });

  // The #713 choke point: `rawStubHeaders` is the stub's REAL Headers; the
  // proxy below is the only view reachable from consumer code, and its
  // mutating methods consult the cached-scope guard first. shadowStubHeaders
  // shadows `headers` on the stub Response INSTANCE (a real Response, not a
  // facade — safe to hand to the platform), so every surface that ends in a
  // stub-header mutation — ctx.header/setCookie/deleteCookie, ctx.setTheme,
  // the handler ctx.headers proxy, and raw `ctx.res.headers.set(...)` — is
  // guarded at the mutation itself, not per enumerated wrapper. Guard-exempt
  // internal writers (_rotateStateCookie, _setKeepCacheDirective — serve
  // machinery, documented callable from loaders/during capture) write to
  // rawStubHeaders directly. The serve/commit path's stub reads and its
  // Set-Cookie drain (rsc/helpers.ts) run outside any latched funnel scope,
  // where assertCachedHeaderWriteAllowed is a no-op.
  let rawStubHeaders = stubResponse.headers;
  // Node's util.inspect unwraps this Proxy and calls undici's Headers hook
  // with the proxy as `this`. That reads `#headersList` and throws (#1000).
  // Inspect does not consult the get trap, so the hook is an own property of
  // the target and formats `rawStubHeaders`. Read on each call: setStatus
  // rebinds that let to a new Headers.
  const NODE_INSPECT = Symbol.for("nodejs.util.inspect.custom");
  const guardedStubHeaders: Headers = new Proxy(new Headers(), {
    get(_target, prop) {
      const raw = rawStubHeaders;
      const value = Reflect.get(raw, prop) as unknown;
      if (typeof value !== "function") return value;
      if (prop === "set" || prop === "append" || prop === "delete") {
        return (...args: unknown[]) => {
          assertCachedHeaderWriteAllowed("response headers", prop);
          return (value as (...a: unknown[]) => unknown).apply(raw, args);
        };
      }
      return (value as (...a: unknown[]) => unknown).bind(raw);
    },
  });
  Object.defineProperty(guardedStubHeaders, NODE_INSPECT, {
    value(...args: unknown[]): unknown {
      const hook = (rawStubHeaders as unknown as Record<symbol, unknown>)[
        NODE_INSPECT
      ];
      if (typeof hook === "function") return hook.apply(rawStubHeaders, args);
      // DOM Headers has forEach and not entries. Node always has the hook above.
      const listed: Record<string, string> = {};
      rawStubHeaders.forEach((value, key) => {
        listed[key] = value;
      });
      return listed;
    },
    configurable: true,
    writable: true,
  });
  const shadowStubHeaders = (res: Response): void => {
    Object.defineProperty(res, "headers", {
      value: guardedStubHeaders,
      enumerable: true,
      configurable: true,
    });
  };
  shadowStubHeaders(stubResponse);
  // Rebuild the stub with a new status, re-shadowing the fresh instance
  // (the Response constructor copies rawStubHeaders into new raw Headers).
  const replaceStubStatus = (status: number): void => {
    stubResponse = new Response(null, { status, headers: rawStubHeaders });
    rawStubHeaders = stubResponse.headers;
    shadowStubHeaders(stubResponse);
  };

  const handleStore = createHandleStore();
  const loaderPromises = new Map<string, Promise<any>>();

  const getParsedCookies = (): Record<string, string> => {
    if (!parsedCookies) {
      parsedCookies = parseCookiesFromHeader(cookieHeader);
    }
    return parsedCookies;
  };

  let responseCookieCache: Map<string, string | null> | null = null;
  const getResponseCookies = (): Map<string, string | null> => {
    if (!responseCookieCache) {
      responseCookieCache = parseResponseCookies(stubResponse);
    }
    return responseCookieCache;
  };
  const invalidateResponseCookieCache = () => {
    responseCookieCache = null;
  };

  // Guard for the two response-write surfaces that are NOT Headers mutations
  // (setStatus rebuilds the stub Response, onResponse registers a callback) —
  // these can't ride the guarded-headers choke point above, so they stay
  // enumerated. Same unified #713 guard, same message family.
  function assertResponseWriteAllowed(methodName: string): void {
    assertCachedHeaderWriteAllowed("ctx", methodName);
  }

  // Response stub Set-Cookie wins, then original header (source of truth for mutations).
  const effectiveCookie = (name: string): string | undefined => {
    const mutations = getResponseCookies();
    if (mutations.has(name)) {
      const v = mutations.get(name);
      return v === null ? undefined : v;
    }
    return getParsedCookies()[name];
  };

  // The effective jar: request cookies minus deletions plus same-request writes.
  const effectiveCookies = (): Record<string, string> => {
    const parsed = getParsedCookies();
    const mutations = getResponseCookies();
    if (mutations.size === 0) return { ...parsed };
    // Build result without delete (avoids V8 dictionary-mode de-opt)
    const deleted = new Set<string>();
    for (const [k, v] of mutations) {
      if (v === null) deleted.add(k);
    }
    const result: Record<string, string> = {};
    for (const key of Object.keys(parsed)) {
      if (!deleted.has(key)) result[key] = parsed[key];
    }
    for (const [k, v] of mutations) {
      if (v !== null) result[k] = v;
    }
    return result;
  };

  const getTheme = (): Theme | undefined => {
    if (!themeConfig) return undefined;

    const stored = effectiveCookie(themeConfig.storageKey);
    if (stored) {
      if (stored === "system" && themeConfig.enableSystem) {
        return "system";
      }
      if (themeConfig.themes.includes(stored)) {
        return stored as Theme;
      }
    }
    return themeConfig.defaultTheme;
  };

  const setTheme = (theme: Theme): void => {
    if (!themeConfig) return;

    // Shared guard (isValidTheme): reject any value not in the configured theme
    // set, AND reject "system" when system detection is off — a cookie of
    // theme=system with enableSystem:false would re-apply a bogus class="system"
    // on the next SSR.
    if (!isValidTheme(theme, themeConfig)) {
      warnInvalidTheme(theme, themeConfig);
      return;
    }

    stubResponse.headers.append(
      "Set-Cookie",
      serializeCookieValue(themeConfig.storageKey, theme, {
        path: THEME_COOKIE.path,
        maxAge: THEME_COOKIE.maxAge,
        sameSite: THEME_COOKIE.sameSite,
      }),
    );
    invalidateResponseCookieCache();
  };

  const cleanUrl = stripInternalParams(url);

  const ctx: RequestContext<TEnv> = {
    env,
    request,
    url: cleanUrl,
    originalUrl: new URL(request.url),
    pathname: url.pathname,
    searchParams: cleanUrl.searchParams,
    _variables: variables,
    build,
    dynamic(): void {
      ctx._dynamic = true;
      // A dynamic() render is always live (never a shell HIT), so its handler
      // header writes are deterministic — clear the ppr latch to re-permit them
      // (#735). No-op from middleware (outside the funnel scope) or on non-ppr
      // routes; cache() latches are left alone.
      clearPprHeaderScope();
    },
    _dynamic: false,
    get: ((keyOrVar: any) => {
      if (isNonCacheable(variables, keyOrVar)) {
        assertNonCacheableReadAllowed(keyOrVar, _getRequestContext());
      }
      return contextGet(variables, keyOrVar);
    }) as RequestContext<TEnv>["get"],
    set: ((keyOrVar: any, value: any, options?: any) => {
      assertNotInsideCacheExec(ctx, "set");
      contextSet(variables, keyOrVar, value, options);
    }) as RequestContext<TEnv>["set"],
    params: {} as Record<string, string>,

    get res(): Response {
      return stubResponse;
    },
    set res(_: Response) {
      throw new Error(
        "ctx.res is read-only. Use ctx.header() to set response headers, or cookies() for cookie mutations.",
      );
    },

    // The visitor's cookies, guarded like cookies() (#976): before, a plain
    // read that a ppr shell, a cache() entry or a "use cache" entry stored
    // for every visitor.
    cookie(name: string): string | undefined {
      guardRawCookieRead(ctx, "getRequestContext().cookie()");
      return effectiveCookie(name);
    },

    cookies(): Record<string, string> {
      guardRawCookieRead(ctx, "getRequestContext().cookies()");
      return effectiveCookies();
    },

    // Non-enumerable, defined after this literal.
    _readCookie: effectiveCookie,
    _readCookies: effectiveCookies,

    setCookie(name: string, value: string, options?: CookieOptions): void {
      assertNotInsideCacheExec(ctx, "setCookie");
      stubResponse.headers.append(
        "Set-Cookie",
        serializeCookieValue(name, value, options),
      );
      invalidateResponseCookieCache();
    },

    deleteCookie(
      name: string,
      options?: Pick<CookieOptions, "domain" | "path">,
    ): void {
      assertNotInsideCacheExec(ctx, "deleteCookie");
      stubResponse.headers.append(
        "Set-Cookie",
        serializeCookieValue(name, "", { ...options, maxAge: 0 }),
      );
      invalidateResponseCookieCache();
    },

    header(name: string, value: string): void {
      assertNotInsideCacheExec(ctx, "header");
      stubResponse.headers.set(name, value);
    },

    // Rotate the rango state cookie for the responding client (the server seat
    // of invalidateClientCache). Writes ONE Set-Cookie per request with the
    // value {version}:{timestamp}; the `:` stays raw (the cookie-name.ts
    // serializer), not the URL-encoded form serializeCookieValue would produce.
    // The timestamp is strictly greater than the client's current one (inbound
    // X-Rango-State), so a same-millisecond server rotation still differs from
    // the client value and the divergence observer fires.
    _rotateStateCookie(): void {
      if (rangoStateRotated) return;
      rangoStateRotated = true;
      if (!stateCookieName) return;
      // The client's current value, for the monotonic guard: prefer the
      // X-Rango-State header (router navigation/prefetch fetches send it), but
      // fall back to the request's rango state cookie — action POSTs / plain
      // app fetch()s carry no router header yet DO send the cookie. Without the
      // fallback, prevTs stays 0 and a same-ms mint can equal the client value,
      // leaving the divergence observer silent. `|| null` so an empty header
      // ('' from proxy normalization) falls through instead of short-circuiting.
      // getRawCookieValue reads the cookie undecoded (the wire value
      // decodeStateValue decodes exactly once) AND is the same parser the client
      // mirror uses, so both seats read the same jar entry.
      const prevRaw =
        (requestHeaders(request).get("x-rango-state") || null) ??
        getRawCookieValue(cookieHeader, stateCookieName);
      const value = mintStateValue(versions?.document ?? "0", prevRaw);
      // rawStubHeaders: guard-exempt internal writer — invalidateClientCache()
      // is documented callable from loaders and during shell capture.
      rawStubHeaders.append(
        "Set-Cookie",
        serializeStateCookie(stateCookieName, value, url.protocol === "https:"),
      );
      invalidateResponseCookieCache();
    },

    // Set the keepClientCache() directive header. The action bridge reads it on
    // the response and suppresses its automatic invalidation. `.set` makes this
    // idempotent (one header regardless of call count). rawStubHeaders:
    // guard-exempt internal writer.
    _setKeepCacheDirective(): void {
      rawStubHeaders.set(KEEP_CACHE_HEADER, "1");
    },

    // The fresh-reads cookie (browser/cookie-name.ts): one Set-Cookie per
    // response, the longest Max-Age any invalidation asked for. HttpOnly (the
    // client never reads it), SameSite=Lax, Path=/. rawStubHeaders: an
    // internal writer, allowed wherever updateTag()/revalidateTag() are. A
    // shared cache never stores it (Set-Cookie is a per-client signal).
    _setFreshReadsCookie(maxAgeMs: number): void {
      if (!freshCookie) return;
      const maxAge = Math.ceil(maxAgeMs / 1000);
      // Already set for at least this long (an earlier invalidation in this
      // request): nothing to add, sent or not.
      if (maxAge <= freshCookieMaxAge) return;
      if (ctx._responseSent) {
        // A streaming loader or render: the headers already left. The
        // invalidation itself still ran; only the mutating user's bypass of
        // the stores' isolate memos is lost.
        if (process.env.NODE_ENV !== "production") {
          console.warn(
            `[rango] updateTag()/revalidateTag() ran after the response ` +
              `headers were sent (from a streaming loader or render), so the ` +
              `${freshCookie} cookie was not set: this user's next requests ` +
              `can be served from a store's isolate memo for a few seconds. ` +
              `Invalidate in a server action, a route handler, or middleware.`,
          );
        }
        return;
      }
      const serialized = (age: number) =>
        `${freshCookie}=1; Max-Age=${age}; Path=/; HttpOnly; SameSite=Lax` +
        (url.protocol === "https:" ? "; Secure" : "");
      if (freshCookieMaxAge > 0) {
        const prior = serialized(freshCookieMaxAge);
        const kept = rawStubHeaders
          .getSetCookie()
          .filter((cookie) => cookie !== prior);
        rawStubHeaders.delete("Set-Cookie");
        for (const cookie of kept) rawStubHeaders.append("Set-Cookie", cookie);
      }
      freshCookieMaxAge = maxAge;
      rawStubHeaders.append("Set-Cookie", serialized(maxAge));
      invalidateResponseCookieCache();
    },

    setStatus(status: number): void {
      assertNotInsideCacheExec(ctx, "setStatus");
      assertResponseWriteAllowed("setStatus");
      replaceStubStatus(status);
    },

    _setStatus(status: number): void {
      replaceStubStatus(status);
    },

    use: null as any,

    method: request.method,

    _handleStore: handleStore,
    _cacheStore: cacheStore,
    _versions: versions,
    _searchParamsFilter: searchParamsFilter,
    _explicitTaggedStores: explicitTaggedStores,
    _requestTags: new Set<string>(),
    _cacheProfiles: cacheProfiles,
    _freshReads:
      freshCookie !== undefined &&
      getRawCookieValue(cookieHeader, freshCookie) !== null,

    waitUntil(fn: () => Promise<void>): void {
      if (ctx.build) return;
      // A deferred task does not rely on the platform carrying the request's
      // async context into it. Deployed workerd lost it once ("use cache"
      // background revalidation, cache-runtime.ts); Node and miniflare never
      // do, so no local run shows a loss. A cache store builds its key inside
      // the task and reads the serving router's versions and the request host
      // from the context: without it the write lands under the whole-build
      // pair, which no router with its own version reads. So the task
      // re-enters the context it was scheduled under: the store active then
      // (a derived context), else this one.
      const scheduledUnder = requestContextStorage.getStore() ?? ctx;
      // Wrap in Promise.resolve().then(...) so a SYNCHRONOUS throw in a
      // non-async callback becomes a rejected promise handed to the host's
      // waitUntil (logged as a background failure), instead of escaping into
      // the request flow. Mirrors fireAndForgetWaitUntil's deferral.
      const task = Promise.resolve().then(() =>
        requestContextStorage.run(scheduledUnder, fn),
      );
      // Track the task promise so the PPR shell capture can settle the
      // foreground's deferred cache writes before its own match/render (the
      // ordering edge; see _pendingBackgroundTasks). The capture task itself
      // opts out via the marker — the drain must never await its own promise.
      if (
        !(fn as { [UNTRACKED_BACKGROUND_TASK]?: boolean })[
          UNTRACKED_BACKGROUND_TASK
        ]
      ) {
        ctx._pendingBackgroundTasks?.push(task);
      }
      if (executionContext?.waitUntil) {
        executionContext.waitUntil(task);
      } else {
        // Node/dev fallback: fire-and-forget with error logging (the same
        // policy fireAndForgetWaitUntil applies).
        task.catch((err) =>
          console.error("[waitUntil] Background task failed:", err),
        );
      }
    },

    executionContext,

    _onResponseCallbacks: [],
    _pendingBackgroundTasks: [],

    onResponse(callback: (response: Response) => Response): void {
      assertNotInsideCacheExec(ctx, "onResponse");
      assertResponseWriteAllowed("onResponse");
      this._onResponseCallbacks.push(callback);
    },

    // theme: a guarded, non-enumerable getter defined after this literal.
    _readTheme: getTheme,
    setTheme: themeConfig
      ? (theme: Theme) => {
          assertNotInsideCacheExec(ctx, "setTheme");
          setTheme(theme);
        }
      : undefined,
    _themeConfig: themeConfig,

    setLocationState(entries: LocationStateEntry | LocationStateEntry[]): void {
      assertNotInsideCacheExec(ctx, "setLocationState");
      const arr = Array.isArray(entries) ? entries : [entries];
      this._locationState = this._locationState
        ? [...this._locationState, ...arr]
        : arr;
    },
    _locationState: undefined,

    _reportedErrors: new WeakSet<object>(),
    _renderErrors: [],
    _metricsStore: undefined,
    _renderForeground: undefined,
    _activeRoutine: undefined,
    _renderDiagnosticsEnabled: undefined,
    _handlerStart: undefined,

    _renderBarrier: null as any,
    _resolveRenderBarrier: null as any,
    _renderBarrierSegmentOrder: undefined,

    reverse: createReverseFunction(getGlobalRouteMap(), undefined, {}),
  };

  wireRenderBarrier(ctx, handleStore);

  ctx.use = createUseFunction({
    handleStore,
    loaderPromises,
    getContext: () => ctx,
  });

  // getRequestContext().theme is the visitor's cookie, guarded like cookies()
  // (#971); before it was a plain read that a ppr shell, a cache() entry or a
  // "use cache" entry stored for every visitor. Non-enumerable like the
  // handler ctx.theme (handler-context.ts THEME_DESCRIPTOR): serializing the
  // context (React dev debug info) must not count as a read. The guard reads
  // the ambient context, as cookies() does, and falls back to the receiver.
  // _readTheme is the unguarded read: non-enumerable too, so a spread copy of
  // the context (the fetchable-loader ctx, loader-fetch.ts) cannot carry it.
  // The same holds for the unguarded cookie reads (#976).
  Object.defineProperties(ctx, {
    theme: {
      get(this: RequestContext<TEnv>): Theme | undefined {
        return readGuardedTheme(this, "getRequestContext().theme");
      },
      enumerable: false,
      configurable: true,
    },
    _readTheme: { enumerable: false },
    _readCookie: { enumerable: false },
    _readCookies: { enumerable: false },
  });

  (ctx as any)[NOCACHE_SYMBOL] = true;
  // Non-enumerable: a self-reference would make the context circular for
  // JSON.stringify, spreads and React's dev debug-info serialization of props.
  Object.defineProperty(ctx, "_requestRoot", {
    value: ctx,
    enumerable: false,
    configurable: true,
    writable: true,
  });
  ctx._requestStart = executionStart();
  return ctx;
}

/**
 * Wire a fresh render barrier onto `ctx`, closure-bound to THIS ctx and THIS
 * handle store. Called by createRequestContext for every fresh context, and by
 * deriveShellCaptureContext (rsc/shell-capture.ts) for the PPR capture's
 * derived context.
 *
 * The derived-context call is load-bearing (issue #684, plan 009): the capture
 * context is `Object.create(reqCtx)`, so without its own wiring every
 * `_renderBarrier*` read fell through the prototype to the FOREGROUND
 * request's barrier — whose getter and resolver are closure-bound to the
 * foreground ctx and its handle store, and whose resolver no-ops once
 * resolved. A bake-lane loader's `await ctx.rendered()` during capture then
 * resolved instantly against the foreground's barrier and `ctx.use(handle)`
 * read the foreground's handle snapshot; the capture's fresh `_handleStore`
 * was invisible, so foreground per-request handle data could bake into the
 * shared shell.
 */
export function wireRenderBarrier(
  ctx: RequestContext<any, any>,
  handleStore: HandleStore,
): void {
  // Reset the whole barrier family as OWN properties. No-op for a fresh
  // context; for the derived capture context this shadows the foreground's
  // resolved state so the capture runs its own barrier lifecycle. In
  // particular _treeHasStreaming must be recomputed for the CAPTURE's tree
  // (cache-lookup/segment-resolution only set it when undefined): an
  // inherited `true` made a capture-lane rendered() seal the capture's fresh
  // store at loader start and pair it with the foreground's segment order.
  ctx._renderBarrierSegmentOrder = undefined;
  ctx._renderBarrierWaiters = undefined;
  ctx._renderBarrierHandleSnapshot = undefined;
  ctx._renderBarrierGuardClosed = undefined;
  ctx._handlerLoaderDeps = undefined;
  ctx._awaitBeforeFlushLoaderIds = undefined;
  ctx._treeHasStreaming = undefined;

  // Lazy allocation: only create the Promise when a loader calls rendered().
  let barrierResolved = false;
  let resolveBarrier: (() => void) | undefined;
  ctx._resolveRenderBarrier = (
    segments: Array<{ type: string; id: string }>,
  ) => {
    if (barrierResolved) return;
    barrierResolved = true;
    const segOrder = segments
      .filter((s) => s.type !== "loader")
      .map((s) => s.id);
    ctx._renderBarrierSegmentOrder = segOrder;

    const closeGuard = () => {
      ctx._renderBarrierWaiters = undefined;
      ctx._handlerLoaderDeps = undefined;
      ctx._renderBarrierGuardClosed = true;
    };

    if (ctx._treeHasStreaming) {
      handleStore.settled.then(closeGuard);
    } else {
      ctx._renderBarrierHandleSnapshot = buildHandleSnapshot(
        handleStore,
        segOrder,
      );
      closeGuard();
    }
    if (resolveBarrier) resolveBarrier();
  };
  // defineProperty, not assignment: on a derived context the prototype's
  // _renderBarrier may already be a non-writable data property (the getter
  // pins it after first access), which would reject a plain assignment.
  Object.defineProperty(ctx, "_renderBarrier", {
    get() {
      const p = barrierResolved
        ? Promise.resolve()
        : new Promise<void>((resolve) => {
            resolveBarrier = resolve;
          });
      Object.defineProperty(ctx, "_renderBarrier", {
        value: p,
        writable: false,
        configurable: false,
      });
      return p;
    },
    configurable: true,
  });
}

// Capture the Max-Age value so it can be parsed numerically. A leading zero
// (Max-Age=05) is a non-zero lifetime, not a deletion; only a value that parses
// to <= 0 marks a cookie for deletion. Pattern-matching a leading "0" misread
// zero-prefixed values like 05 / 010 as deletions.
const MAX_AGE_RE = /;\s*Max-Age\s*=\s*(-?\d+)/i;

function isCookieDeletion(header: string): boolean {
  const m = MAX_AGE_RE.exec(header);
  if (!m) return false;
  return Number(m[1]) <= 0;
}

function parseResponseCookies(response: Response): Map<string, string | null> {
  const result = new Map<string, string | null>();
  const setCookies = response.headers.getSetCookie();

  for (const header of setCookies) {
    const semiIdx = header.indexOf(";");
    const pair = semiIdx === -1 ? header : header.substring(0, semiIdx);
    const eqIdx = pair.indexOf("=");
    if (eqIdx === -1) continue;

    let name: string;
    let value: string;
    try {
      name = decodeURIComponent(pair.substring(0, eqIdx).trim());
      value = decodeURIComponent(pair.substring(eqIdx + 1).trim());
    } catch {
      continue;
    }

    const isDeleted = isCookieDeletion(header);
    result.set(name, isDeleted ? null : value);
  }

  return result;
}

// Re-exported for unit tests and the existing import path. The implementation
// lives in the dependency-free ./cookie-parse leaf so consumers (e.g. the host
// dispatcher) can share it without pulling this module's request-context graph.
export { parseCookiesFromHeader };

/** Reject CR/LF/;/,/whitespace/control so raw attribute interpolation cannot inject. */
function assertSafeCookieAttribute(
  value: string,
  label: "domain" | "path",
): void {
  for (let i = 0; i < value.length; i++) {
    const code = value.charCodeAt(i);
    if (code <= 0x20 || code === 0x7f || value[i] === ";" || value[i] === ",") {
      throw new Error(
        label === "domain" ? "invalid cookie domain" : "invalid cookie path",
      );
    }
  }
}

export function serializeCookieValue(
  name: string,
  value: string,
  options: CookieOptions = {},
): string {
  let cookie = `${encodeURIComponent(name)}=${encodeURIComponent(value)}`;

  if (options.domain) {
    assertSafeCookieAttribute(options.domain, "domain");
    cookie += `; Domain=${options.domain}`;
  }
  if (options.path) {
    if (!options.path.startsWith("/")) {
      throw new Error("invalid cookie path");
    }
    assertSafeCookieAttribute(options.path, "path");
    cookie += `; Path=${options.path}`;
  }
  if (options.maxAge !== undefined) {
    // Safe integer: Number.isInteger(1e21) is true but stringifies as "1e+21",
    // which is invalid Max-Age wire syntax. Number.isSafeInteger rejects that.
    if (
      typeof options.maxAge !== "number" ||
      !Number.isSafeInteger(options.maxAge)
    ) {
      throw new Error("invalid cookie maxAge");
    }
    cookie += `; Max-Age=${options.maxAge}`;
  }
  if (options.expires) cookie += `; Expires=${options.expires.toUTCString()}`;
  if (options.httpOnly) cookie += "; HttpOnly";
  if (options.secure) cookie += "; Secure";
  if (options.sameSite) {
    if (
      options.sameSite !== "strict" &&
      options.sameSite !== "lax" &&
      options.sameSite !== "none"
    ) {
      throw new Error("invalid cookie sameSite");
    }
    cookie += `; SameSite=${options.sameSite}`;
  }

  return cookie;
}

/**
 * Options for creating the use() function
 */
export interface CreateUseFunctionOptions<TEnv> {
  handleStore: HandleStore;
  loaderPromises: Map<string, Promise<any>>;
  getContext: () => RequestContext<TEnv>;
}

export function createUseFunction<TEnv>(
  options: CreateUseFunctionOptions<TEnv>,
): RequestContext["use"] {
  const { handleStore, loaderPromises, getContext } = options;

  return ((item: LoaderDefinition<any, any> | Handle<any, any>) => {
    if (isHandle(item)) {
      const handle = item;
      const ctx = getContext();
      const segmentId = (ctx as any)._currentSegmentId;

      if (!segmentId) {
        throw new Error(
          `Handle "${handle.$$id}" used outside of handler context. ` +
            `Handles must be used within route/layout handlers.`,
        );
      }

      return withDefer(
        (dataOrFn: unknown | Promise<unknown> | (() => Promise<unknown>)) => {
          const valueOrPromise =
            typeof dataOrFn === "function"
              ? (dataOrFn as () => Promise<unknown>)()
              : dataOrFn;

          handleStore.push(handle.$$id, segmentId, valueOrPromise);
        },
      );
    }

    const loader = item as LoaderDefinition<any, any>;

    const memo = loaderPromises.get(loader.$$id);
    if (memo) {
      // Same refusal as the handler ctx.use memo hit (#1011): a "use cache"
      // body reading a value whose run read request identity.
      return readStartedLoaderValue(memo, loader.$$id);
    }

    let loaderFn = loader.fn;
    if (!loaderFn) {
      const fetchable = getFetchableLoader(loader.$$id);
      if (fetchable) {
        loaderFn = fetchable.fn;
      }
    }

    if (!loaderFn) {
      throw new Error(
        `Loader "${loader.$$id}" has no function. This usually means the loader was defined without "use server" and the function was not included in the build.`,
      );
    }

    const ctx = getContext();

    // Build the typed ctx.search the same way the render path
    // (createHandlerContext) and the fetchable-loader path (loader-fetch.ts) do:
    // parse the route's search schema over the cleaned searchParams. The base
    // RequestContext carries no `search` field, so reading `(ctx as any).search`
    // here always yielded {} — dropping typed search for action/dispatch loaders.
    const searchSchema = ctx._routeName
      ? getSearchSchema(ctx._routeName, ctx._routerId)
      : undefined;
    const loaderSearch = searchSchema
      ? parseSearchParams(ctx.searchParams, searchSchema)
      : {};

    const loaderCtx: LoaderContext<Record<string, string | undefined>, TEnv> & {
      _routeName?: string;
    } = {
      params: ctx.params,
      routeParams: (ctx.params ?? {}) as Record<string, string>,
      request: ctx.request,
      searchParams: ctx.searchParams,
      search: loaderSearch,
      pathname: ctx.pathname,
      url: ctx.url,
      originalUrl: ctx.originalUrl,
      env: ctx.env as any,
      waitUntil: ctx.waitUntil.bind(ctx),
      executionContext: ctx.executionContext,
      get: ((keyOrVar: any) => {
        // Handle READS need the rendered() barrier, which this lane
        // (action/dispatch-invoked loaders) does not run. Fail with guidance
        // instead of returning a misleading empty collect.
        if (isHandle(keyOrVar)) {
          throw new Error(
            `ctx.get(handle) is only available in DSL loaders after ` +
              `"await ctx.rendered()". It cannot be used from request-context ` +
              `loaders or server actions.`,
          );
        }
        return (ctx.get as any)(keyOrVar);
      }) as any,
      // Pass items through: loaders delegate to the request ctx's loader
      // executor; a handle yields the ctx's push function (write parity —
      // ctx.use(Meta)({...}) works in this lane exactly like in a handler).
      use: ((item: any) => ctx.use(item)) as LoaderContext["use"],
      method: "GET",
      body: undefined,
      reverse: createReverseFunction(
        getGlobalRouteMap(),
        ctx._routeName,
        ctx.params as Record<string, string>,
        ctx._routeName
          ? isRouteRootScoped(ctx._routeName, ctx._routerId)
          : undefined,
      ),
      _routeName: ctx._routeName,
      rendered: () => {
        throw new Error(
          `ctx.rendered() is only available in DSL loaders (registered via loader() in urls()). ` +
            `It cannot be used from request-context loaders or server actions.`,
        );
      },
    };
    // "use cache" keys it by route, like the request ctx it reads (#940).
    (loaderCtx as any)[NOCACHE_SYMBOL] = true;

    // Meter through the same unified phase API as the loader-resolution funnel
    // (observePhase), so a loader resolved via this base request-context ctx.use
    // co-emits the "loader:<id>" perf metric AND the "rango.loader" span — no
    // drift between the two ctx.use implementations.
    const run: LoaderRunIdentity = { loaderId: loader.$$id };
    const promise = observePhase(PHASES.loader(loader.$$id), () =>
      Promise.resolve(runInsideLoaderRun(run, () => loaderFn(loaderCtx))),
    );
    trackLoaderRun(promise, run);

    loaderPromises.set(loader.$$id, promise);

    return promise;
  }) as RequestContext["use"];
}
