// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/about",
  "api.status": "/api/status",
  "group.index": "/g/:id",
  "group.section.item.leaf": "/g/:id/sub/leaf",
  home: "/",
} as const;

// Aliased so the augmentation below does not pay a homomorphic mapped-type
// instantiation per route; `as const` already makes the members readonly.
type NamedRoutesShape = typeof NamedRoutes;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends NamedRoutesShape {}
  }
}
