// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/about",
  "api.status": "/api/status",
  "group.index": "/g/:id",
  "group.section.item.leaf": "/g/:id/sub/leaf",
  home: "/",
} as const;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
