// Auto-generated by @rangojs/router - do not edit
export const routes = {
  health: "/health",
  productDetail: "/products/:id",
  products: "/products",
} as const;
export type routes = typeof routes;
