import { expect, test } from "@playwright/test";
import fs from "node:fs/promises";
import path from "node:path";

const genFilePath = path.resolve("./src/router.named-routes.gen.ts");

// Shared assertions for both dev and production — the gen file should be
// identical regardless of which mode wrote it last.
async function assertGenFileHeader() {
  const content = await fs.readFile(genFilePath, "utf-8");
  expect(content).toContain("// Auto-generated by @rangojs/router");
  expect(content).toContain("export const NamedRoutes");
  expect(content).toContain("namespace RSCRouter");
  expect(content).toContain("interface GeneratedRouteMap");
}

async function assertDocsRoutes() {
  const content = await fs.readFile(genFilePath, "utf-8");
  // These routes come from createDocsPatterns() factory and require
  // runtime discovery (static parser cannot resolve factory calls).
  expect(content).toContain('"docs.index": "/docs"');
  expect(content).toContain('"docs.detail": "/docs/:slug"');
  expect(content).toContain('"docs.raw": "/docs/:slug/raw"');
  expect(content).toContain('"docs.refIndex": "/docs/ref"');
  expect(content).toContain('"docs.refDetail": "/docs/ref/:slug"');
  expect(content).toContain('"docs.search": "/docs/api/search"');
}

async function assertCoreRoutes() {
  const content = await fs.readFile(genFilePath, "utf-8");
  expect(content).toContain('home: "/"');
  expect(content).toContain('about: "/about"');
  expect(content).toContain('counter: "/counter"');
  expect(content).toContain('"api.health": "/api/health"');
  expect(content).toContain('blog: "/blog"');
  expect(content).toContain('blogPost: "/blog/:slug"');
}

async function assertNoDoubleSlash() {
  const content = await fs.readFile(genFilePath, "utf-8");
  const doubleSlashLines = content.match(/: "\/\//gm);
  expect(doubleSlashLines).toBeNull();
}

// Dev mode: the gen file is written by discover() using a temp Node.js server
// in Cloudflare dev (workerd has no module runner).
test.describe("route-types", () => {
  test("should generate named-routes file with auto-generated header", assertGenFileHeader);
  test("should contain docs.* routes from factory function", assertDocsRoutes);
  test("should contain core application routes", assertCoreRoutes);
  test("should not have double-slash patterns", assertNoDoubleSlash);
});

// Production: the gen file is written by buildStart() using a temp Vite server.
// Verify that the same routes are present — build and dev must produce
// identical output.
test.describe("route-types (production)", () => {
  test("should generate named-routes file with auto-generated header (production)", assertGenFileHeader);
  test("should contain docs.* routes from factory function (production)", assertDocsRoutes);
  test("should contain core application routes (production)", assertCoreRoutes);
  test("should not have double-slash patterns (production)", assertNoDoubleSlash);
});
