import { describe, it, expect } from "vitest";
import {
  isAutoGeneratedRouteName,
  validateUserRouteName,
  AUTO_GENERATED_ROUTE_PREFIX,
  INTERNAL_INCLUDE_SCOPE_PREFIX,
} from "../route-name.js";

describe("isAutoGeneratedRouteName", () => {
  it("detects $path_ prefix", () => {
    expect(isAutoGeneratedRouteName("$path__health")).toBe(true);
  });

  it("detects $path_ in nested name", () => {
    expect(isAutoGeneratedRouteName("docs.$path__health")).toBe(true);
  });

  it("detects $prefix_ prefix", () => {
    expect(isAutoGeneratedRouteName("$prefix_0.index")).toBe(true);
  });

  it("detects $prefix_ in nested name", () => {
    expect(isAutoGeneratedRouteName("blog.$prefix_1.post")).toBe(true);
  });

  it("allows normal user names", () => {
    expect(isAutoGeneratedRouteName("home")).toBe(false);
    expect(isAutoGeneratedRouteName("shop.products")).toBe(false);
  });

  it("allows user names containing $ that don't match reserved prefixes", () => {
    expect(isAutoGeneratedRouteName("docs.$admin")).toBe(false);
    expect(isAutoGeneratedRouteName("$custom")).toBe(false);
  });
});

describe("validateUserRouteName", () => {
  it("allows normal names", () => {
    expect(() => validateUserRouteName("home")).not.toThrow();
    expect(() => validateUserRouteName("shop")).not.toThrow();
    expect(() => validateUserRouteName("$custom")).not.toThrow();
  });

  it(`rejects names starting with "${AUTO_GENERATED_ROUTE_PREFIX}"`, () => {
    expect(() => validateUserRouteName("$path_admin")).toThrow(
      /reserved internal prefix/,
    );
  });

  it(`rejects names starting with "${INTERNAL_INCLUDE_SCOPE_PREFIX}"`, () => {
    expect(() => validateUserRouteName("$prefix_admin")).toThrow(
      /reserved internal prefix/,
    );
    expect(() => validateUserRouteName("$prefix_0")).toThrow(
      /reserved internal prefix/,
    );
  });

  it("rejects reserved prefix in any dot-separated segment", () => {
    expect(() => validateUserRouteName("foo.$prefix_admin")).toThrow(
      /reserved internal prefix/,
    );
    expect(() => validateUserRouteName("docs.$path_meta")).toThrow(
      /reserved internal prefix/,
    );
    expect(() => validateUserRouteName("a.b.$prefix_0.c")).toThrow(
      /reserved internal prefix/,
    );
  });

  it("allows names with $ that don't match reserved prefixes", () => {
    expect(() => validateUserRouteName("docs.$admin")).not.toThrow();
    expect(() => validateUserRouteName("foo.$bar.baz")).not.toThrow();
  });
});
