// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  home: "/app-b",
  page: "/app-b/page",
} as const;

declare global {
  namespace RSCRouter {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
