// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  home: "/app-a",
  page: "/app-a/page",
} as const;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
