/**
 * Phase + event instrumentation — the single internal API for observing router
 * work.
 *
 * The router exposes the same work on three surfaces, and the rule is: each
 * surface has exactly one owner here, so they cannot drift.
 *
 *   - observePhase(): a span of work. Co-emits the `debugPerformance` perf
 *     metric (metrics store -> [RSC Perf] timeline + Server-Timing) AND the
 *     platform span (tracing runner -> Cloudflare custom spans / OTel). From one
 *     wrap site, so the span set is always a subset of the perf phases and the
 *     two can't disagree. Phases that meter their own perf metric with a finer
 *     decomposition (request, middleware) pass `metric: false` and get the span
 *     only — still co-located, still one owner per surface.
 *   - observeEvent(): a discrete fact (TelemetrySink): cache decisions,
 *     revalidation decisions, handler errors, timeouts, origin rejections.
 *     Event-shaped, not phase-shaped — derived from the same call sites but a
 *     separate surface from spans.
 *
 * Why phases, not events, are the parent abstraction: Cloudflare's span API is
 * callback-bound (enterSpan wraps the actual work), so the callback boundary is
 * the source of truth — async-context nesting (a loader's KV/D1/fetch spans
 * landing under rango.loader) cannot be faithfully reconstructed from
 * after-the-fact start/end events. Spans drive; events are emitted alongside.
 *
 * Phase identity lives in the PHASES registry below, so the raw `rango.*` span
 * names, perf-metric labels, and span attributes have a single definition each.
 *
 * When neither perf surface nor tracing is active on the request, observePhase
 * is a direct call — no wrapper, no timestamp, no allocation.
 */

import { _getRequestContext } from "../server/request-context.js";
import { isAutoGeneratedRouteName } from "../route-name.js";
import { getRouterContext } from "./router-context.js";
import { resolveSink, safeEmit, type TelemetryEvent } from "./telemetry.js";
import { appendMetric } from "./metrics.js";
import { type MetricsStore } from "../server/context.js";
import {
  NOOP_TRACE_SPAN,
  traceSpan,
  runThenSettle,
  type TracePhase,
  type TraceSpan,
  type ResolvedTracing,
} from "./tracing.js";
import { isWebSocketUpgradeResponse } from "../response-utils.js";

/**
 * Perf-metric boundary for a phase, or `false` for span-only. `false` means the
 * caller records its own perf metric with a finer decomposition than a single
 * wrap (request: a grand total incl. pre-context bootstrap; middleware: pre/post
 * own-time), so observePhase opens the span but records no metric of its own.
 */
export type PhaseMetric =
  | { label: string | (() => string); depth?: number }
  | false;

/** Describes one observable phase across the perf and span surfaces. */
export interface PhaseSpec {
  /** Perf timeline label + Server-Timing name, or false for span-only. */
  metric: PhaseMetric;
  /** Span phase gate (per-phase toggle in the tracing config). */
  tracePhase: TracePhase;
  /** Span name (rango.*). */
  spanName: string;
  /** Span attributes set automatically when the span opens. */
  attributes?: Record<string, string | number | boolean>;
  /**
   * Span attributes resolved AFTER the wrapped work runs (so they can read state
   * that only exists once the work is underway, e.g. the matched route name).
   * Applied for streaming phases once fn has constructed its value. Return
   * undefined to add nothing.
   */
  lazyAttributes?: () => Record<string, string | number | boolean> | undefined;
}

/**
 * The matched route name for the current request, or undefined when there is no
 * named route (unmatched / auto-generated). Shared by the render phase's metric
 * label and its rango.route span attribute so the two can't disagree.
 */
function currentRouteName(): string | undefined {
  const routeName = _getRequestContext()?._routeName;
  return routeName && !isAutoGeneratedRouteName(routeName)
    ? routeName
    : undefined;
}

/**
 * The router's observable phases. One definition per phase keeps the `rango.*`
 * span names, perf-metric labels, and identifying attributes from spreading
 * across call sites.
 */
export const PHASES = {
  /** Whole request pipeline. Span only — handler:total is metered directly. */
  request: {
    metric: false,
    tracePhase: "request",
    spanName: "rango.request",
  } as PhaseSpec,

  /** One middleware (incl. its downstream onion). Span only — the perf metric
   * is the middleware's exclusive pre/post own-time, recorded directly.
   * `metricLabel` is that metric's label (e.g. "middleware:auth@*"); it doubles
   * as the rango.middleware_name span attribute. */
  middleware: (metricLabel: string): PhaseSpec => ({
    metric: false,
    tracePhase: "middleware",
    spanName: "rango.middleware",
    attributes: { "rango.middleware_name": metricLabel },
  }),

  /** The server-action execution (decode args + run the action body), before
   * the revalidation render. The metric label carries the action id (the
   * _rsc_action / action $$id) so the perf timeline shows WHICH action ran, not
   * just "an action"; the span also gets it as rango.action_id. */
  action: (id: string): PhaseSpec => ({
    metric: { label: `action:${id}` },
    tracePhase: "action",
    spanName: "rango.action",
    attributes: { "rango.action_id": id },
  }),

  /**
   * One loader execution. `depth` is the perf-timeline indentation: 2 (default)
   * for render-time loaders that nest under the render phase; 1 for a standalone
   * fetchable `_rsc_loader` request, which has no render parent.
   */
  loader: (id: string, depth: number = 2): PhaseSpec => ({
    metric: { label: `loader:${id}`, depth },
    tracePhase: "loader",
    spanName: "rango.loader",
    attributes: { "rango.loader_id": id },
  }),

  /** One segment route/layout handler execution (the component/handler that
   * produces a segment). Span only — the perf metric (handler:<id>) is owned by
   * the legacy track() at the same call site, so observePhase here adds the
   * rango.handler span without double-recording. `id` is the segment id, carried
   * as the rango.segment_id attribute to match the handler:<id> perf row. */
  handler: (id: string): PhaseSpec => ({
    metric: false,
    tracePhase: "handler",
    spanName: "rango.handler",
    attributes: { "rango.segment_id": id },
  }),

  /** Whole render phase: match + serialize + SSR. The metric label is resolved
   * lazily at record time (after match has set the route name) so the perf
   * timeline shows WHICH route rendered: `render:total:<routeName>`, falling back
   * to `render:total` when there is no named route (unmatched / auto-generated). */
  render: {
    metric: {
      label: () => {
        const routeName = currentRouteName();
        return routeName ? `render:total:${routeName}` : "render:total";
      },
    },
    tracePhase: "render",
    spanName: "rango.render",
    // Tag the render span with the matched route so the Cloudflare/OTel waterfall
    // shows WHICH route rendered (rango.render + rango.route=index), resolved
    // after match has run. Kept an attribute (not baked into the span name) so the
    // span name stays low-cardinality and aggregatable across routes.
    lazyAttributes: () => {
      const routeName = currentRouteName();
      return routeName ? { "rango.route": routeName } : undefined;
    },
  } as PhaseSpec,

  /** SSR HTML render from the RSC stream. Colon-delimited like the other ssr:*
   * setup metrics (ssr:module-load / ssr:stream-mode). */
  ssr: {
    metric: { label: "ssr:render-html" },
    tracePhase: "ssr",
    spanName: "rango.ssr",
  } as PhaseSpec,
} as const;

/** Apply a phase spec's static attributes to a span (the no-op span ignores them). */
function applyAttributes(
  span: TraceSpan,
  attributes: Record<string, string | number | boolean>,
): void {
  for (const key in attributes) span.setAttribute(key, attributes[key]);
}

/**
 * Record a phase's perf metric for the interval [start, now]. The label may be
 * lazy (resolved here, e.g. render:total needs the route name that match sets
 * partway through the wrapped work).
 */
function recordPhaseMetric(
  store: MetricsStore,
  metric: Exclude<PhaseMetric, false>,
  start: number,
): void {
  const label =
    typeof metric.label === "function" ? metric.label() : metric.label;
  appendMetric(store, label, start, performance.now() - start, metric.depth);
}

/**
 * Instrument one unit of work: open its span AND (unless `metric: false`) record
 * its perf metric, from a single wrap site. fn is invoked exactly once with the
 * span (a no-op span when tracing is off); its return value is returned
 * unchanged and thrown errors / rejected promises propagate unchanged. When fn
 * returns a promise both the metric duration and the span end when it settles.
 *
 * This is the boundary for NON-streaming phases (action, loader): both the span
 * and the metric settle when their own work completes. Streaming phases (request,
 * middleware, render, ssr) use observeRequestPhase / observeStreamingPhase, where
 * the SPAN is held open until body-drain (valid tree) while the perf metric is
 * still recorded at construction (Server-Timing parity).
 *
 * Reads the metrics store + tracing off the RequestContext ALS, which is active
 * for the WHOLE request — contrast observeEvent, which reads the RouterContext
 * ALS (entered later, during match).
 */
export function observePhase<T>(
  spec: PhaseSpec,
  fn: (span: TraceSpan) => T,
): T {
  const reqCtx = _getRequestContext();
  const store = reqCtx?._metricsStore;
  const tracing = reqCtx?._tracing;

  // Neither surface active: direct call, zero overhead.
  if (!store && !tracing) return fn(NOOP_TRACE_SPAN);

  // Attributes only land on a real span, so skip the wrapper when only the perf
  // surface is active (traceSpan would apply them to NOOP_TRACE_SPAN for nothing).
  const attributes = spec.attributes;
  const wrapped: (span: TraceSpan) => T =
    attributes && tracing
      ? (span) => {
          applyAttributes(span, attributes);
          return fn(span);
        }
      : fn;

  const runSpan = (): T =>
    traceSpan(tracing, spec.tracePhase, spec.spanName, wrapped);

  // Span-only — no perf metric to record (metric:false, or perf surface off).
  const metric = spec.metric;
  if (!store || metric === false) return runSpan();

  // Record the phase duration on EVERY termination — success or failure — so a
  // failed loader/render still shows its timing in the perf report (parity with
  // the old track().finally() path it replaced).
  const start = performance.now();
  return runThenSettle(runSpan, () => recordPhaseMetric(store, metric, start));
}

/**
 * Re-stream `response`'s body through a pass-through that fires `onDrain` exactly
 * once when the body finishes — on natural end, a stream error, or a client
 * cancel (so a span can never leak on an aborted response). A bodyless response
 * fires immediately. Only used while instrumentation is active, so the per-chunk
 * relay cost never touches an untraced request.
 */
function instrumentResponseDrain(
  response: Response,
  onDrain: () => void,
): Response {
  // WS-upgrade responses (status 101 / workerd `webSocket` property) must never
  // be reconstructed: `new Response(body, { status: 101 })` throws and a copy
  // drops the non-standard webSocket handoff (the invariant every other Response
  // reconstruction site honors). A bodyless response has nothing to drain.
  const source = response.body;
  if (!source || isWebSocketUpgradeResponse(response)) {
    onDrain();
    return response;
  }
  let fired = false;
  const fire = (): void => {
    if (fired) return;
    fired = true;
    onDrain();
  };
  const reader = source.getReader();
  const wrapped = new ReadableStream<Uint8Array>({
    async pull(controller) {
      try {
        const { done, value } = await reader.read();
        if (done) {
          controller.close();
          fire();
          return;
        }
        controller.enqueue(value);
      } catch (error) {
        controller.error(error);
        fire();
      }
    },
    cancel(reason) {
      fire();
      return reader.cancel(reason);
    },
  });
  return new Response(wrapped, response);
}

/**
 * Shared engine for the streaming phases (request, middleware, render, ssr). It
 * opens the span, runs fn, records the phase's perf metric at CONSTRUCTION (so it
 * still reaches the Server-Timing header / [RSC Perf] table, both built before
 * the body drains), hands the constructed value to the caller via a side channel
 * (streaming preserved), then holds the span open until `drain` resolves. The
 * SPAN therefore ends at body-drain — keeping the trace tree valid (a loader
 * child that resolves mid-stream ends before its parent) — while the perf metric
 * stays the construction work-time. `onDeliver` lets the request phase instrument
 * the final body before handing it back; `onError` lets it release the barrier on
 * failure. Fire-and-forget: the value reaches the caller via the returned
 * promise, so the span promise's rejection is swallowed (already surfaced there).
 */
function runDrainBoundPhase<R>(
  spec: PhaseSpec,
  fn: (span: TraceSpan) => R | Promise<R>,
  tracing: ResolvedTracing | undefined,
  store: MetricsStore | undefined,
  drain: Promise<void>,
  onDeliver: (value: R) => R,
  onError?: () => void,
): Promise<R> {
  let deliver!: (value: R) => void;
  let reject!: (error: unknown) => void;
  const delivered = new Promise<R>((res, rej) => {
    deliver = res;
    reject = rej;
  });

  const start = performance.now();
  const attributes = spec.attributes;
  const metric = spec.metric;
  const record = (): void => {
    if (store && metric !== false) recordPhaseMetric(store, metric, start);
  };
  const spanCallback = async (span: TraceSpan): Promise<void> => {
    if (attributes && tracing) applyAttributes(span, attributes);
    let value: R;
    try {
      value = await fn(span);
    } catch (error) {
      record(); // a failed phase still shows its (construction) timing
      onError?.();
      reject(error);
      throw error; // settle the span with the error, at construction
    }
    // Late attributes (e.g. rango.route) — resolved now that the work has run,
    // so they can read state like the matched route name that match sets midway.
    const lazy =
      tracing && spec.lazyAttributes ? spec.lazyAttributes() : undefined;
    if (lazy) applyAttributes(span, lazy);
    record(); // construction-bound metric, before the response/header is built
    deliver(onDeliver(value));
    await drain; // hold the span open until the response body drains
  };

  traceSpan(tracing, spec.tracePhase, spec.spanName, spanCallback).catch(
    () => {},
  );
  return delivered;
}

/**
 * The request phase (rango.request, metric:false). Owns the drain barrier: it
 * runs fn to construct the final Response, instruments that Response's body so
 * the barrier resolves at drain, hands the Response to the caller immediately
 * (streaming preserved), and holds the span open until the body drains. Every
 * streaming inner phase awaits the same barrier (via observeStreamingPhase), so
 * the request/middleware/render/ssr chain ends at body-drain together and the
 * trace tree is valid (no child span outlives its parent). The perf metrics
 * (render:total, …) are recorded at construction so they still reach the
 * Server-Timing header; only the SPANS are drain-bound. ctx.waitUntil holds the
 * worker alive until drain so the span end runs. Pass-through when no surface is
 * active.
 */
export function observeRequestPhase(
  spec: PhaseSpec,
  fn: (span: TraceSpan) => Promise<Response>,
): Promise<Response> {
  const reqCtx = _getRequestContext();
  const store = reqCtx?._metricsStore;
  const tracing = reqCtx?._tracing;

  if ((!store && !tracing) || !reqCtx) return fn(NOOP_TRACE_SPAN);

  let resolveDrain!: () => void;
  const finalDrain = new Promise<void>((resolve) => {
    resolveDrain = resolve;
  });
  reqCtx._finalDrain = finalDrain;

  // Keep the worker alive until the body drains, so the drain-bound span end
  // (and the inner phases' settle) runs before the runtime can reclaim it.
  const ec = reqCtx.executionContext;
  if (typeof ec?.waitUntil === "function") ec.waitUntil(finalDrain);

  return runDrainBoundPhase<Response>(
    spec,
    fn,
    tracing,
    store,
    finalDrain,
    (response) => instrumentResponseDrain(response, resolveDrain),
    resolveDrain, // release the barrier if fn fails before constructing a body
  );
}

/**
 * A streaming inner phase (rango.middleware / render / ssr). Its SPAN settles
 * when the request's final response body drains (the barrier owned by
 * observeRequestPhase), not when fn returns the constructed stream — so
 * loader/Suspense children that resolve mid-stream nest under a still-open
 * parent. fn's result is delivered at construction (streaming preserved) and the
 * perf metric is recorded at construction (Server-Timing parity). Falls back to
 * observePhase (construction-bound span) when there is no barrier — a
 * non-streaming request, or instrumentation off.
 */
export function observeStreamingPhase<R>(
  spec: PhaseSpec,
  fn: (span: TraceSpan) => R | Promise<R>,
): Promise<R> {
  const reqCtx = _getRequestContext();
  const store = reqCtx?._metricsStore;
  const tracing = reqCtx?._tracing;
  const finalDrain = reqCtx?._finalDrain;

  if ((!store && !tracing) || !finalDrain) {
    return Promise.resolve(observePhase(spec, fn));
  }
  return runDrainBoundPhase<R>(
    spec,
    fn,
    tracing,
    store,
    finalDrain,
    (value) => value,
  );
}

/**
 * Emit one discrete telemetry event (the event-shaped counterpart to
 * observePhase). Resolves the sink from the active router context and stamps the
 * request id when the event omits it. No-op (and total — never throws) when no
 * sink is configured.
 *
 * This is the canonical emitter for SYNCHRONOUS facts that fire inside the
 * request's ALS scope (handler errors, timeouts, origin rejections, revalidation
 * decisions). A few emitters deliberately stay on the lower-level
 * resolveSink + safeEmit because observeEvent's lazy, per-call
 * getRouterContext() read does not fit them — keep this the complete list:
 *   - router.ts wrapLoaderPromise (loader.start/end/error) and
 *     segment-resolution/streamed-handler-telemetry.ts (streamed handler.error)
 *     capture the sink + request id EAGERLY and emit from a fire-and-forget
 *     continuation that runs after the ALS scope may have unwound.
 *   - router/match-handlers.ts resolves the sink ONCE for the hot match-pipeline
 *     loop (request.start/end/error, cache.decision, ...).
 *   - segment-resolution/helpers.ts emits via a caller-provided report.telemetry
 *     sink rather than the ALS router context.
 */
export function observeEvent(event: TelemetryEvent): void {
  // getRouterContext() either throws (real impl, outside a router context — e.g.
  // the build-time prerender path) or returns null/undefined (e.g. mocked).
  // Either way there is no sink to emit to, so swallow and return.
  let routerCtx: ReturnType<typeof getRouterContext> | null | undefined;
  try {
    routerCtx = getRouterContext();
  } catch {
    return;
  }
  if (!routerCtx?.telemetry) return;
  const stamped =
    event.requestId === undefined && routerCtx.requestId !== undefined
      ? ({ ...event, requestId: routerCtx.requestId } as TelemetryEvent)
      : event;
  safeEmit(resolveSink(routerCtx.telemetry), stamped);
}
