/**
 * Router Revalidation Logic
 *
 * Evaluates whether segments should revalidate based on params, actions, and custom functions.
 */

import type { ResolvedSegment, HandlerContext } from "../types";
import type { ActionContext } from "./types";
import {
  debugLog,
  pushRevalidationTraceEntry,
  isTraceActive,
} from "./logging.js";
import type { RevalidationTraceEntry } from "./logging.js";
import { _getRequestContext } from "../server/request-context.js";
import { isAutoGeneratedRouteName } from "../route-name.js";
import { paramsEqual } from "./params-util.js";
import { makeIsAction } from "./is-action.js";

/**
 * Options for revalidation evaluation
 */
interface EvaluateRevalidationOptions<TEnv> {
  /** Current segment to evaluate */
  segment: ResolvedSegment;
  /** Previous route params (from route match, not segment) */
  prevParams: Record<string, string>;
  /** Lazy function to get previous segment if needed */
  getPrevSegment: (() => Promise<ResolvedSegment | undefined>) | null;
  /** Current request */
  request: Request;
  /** Previous URL */
  prevUrl: URL;
  /** Next URL */
  nextUrl: URL;
  /** Custom revalidation functions */
  revalidations: Array<{ name: string; fn: any }>;
  /** Current route key */
  routeKey: string;
  /** Handler context */
  context: HandlerContext<any, TEnv>;
  /** Action context if triggered by action */
  actionContext?: ActionContext;
  /** If true, this is a stale cache revalidation request */
  stale?: boolean;
  /** Trace source hint for the revalidation trace */
  traceSource?: RevalidationTraceEntry["source"];
  /**
   * Override the segment-type-derived default. When set, the value is used as
   * the seed `defaultShouldRevalidate` passed to user revalidate fns and the
   * reason flows into the trace. Callers use this when client-knowledge
   * (e.g. parallel slot not in clientSegmentIds) should dictate the seed
   * instead of the params/method-based heuristic.
   *
   * `floor` makes a `true` seed a guarantee rather than a suggestion: user fns
   * may raise the decision but never lower it. Set it when the segment has no
   * client-side content to fall back on, so a `false` would render nothing
   * instead of keeping a cached copy — see the parallel-slot call site in
   * segment-resolution/revalidation.ts.
   */
  defaultOverride?: { value: boolean; reason: string; floor?: boolean };
}

/**
 * Evaluate if a segment should revalidate using soft/hard decision pattern
 * Optimized to use prevParams directly and avoid building previous segments
 */
export async function evaluateRevalidation<TEnv>(
  options: EvaluateRevalidationOptions<TEnv>,
): Promise<boolean> {
  const {
    segment,
    prevParams,
    getPrevSegment,
    request,
    prevUrl,
    nextUrl,
    revalidations,
    routeKey,
    context,
    actionContext,
    stale,
    traceSource,
    defaultOverride,
  } = options;
  const nextParams = segment.params || {};
  const paramsChanged = !paramsEqual(nextParams, prevParams);
  const searchChanged = prevUrl.search !== nextUrl.search;

  function pushTrace(
    defaultVal: boolean,
    finalVal: boolean,
    reason: string,
  ): void {
    if (!isTraceActive()) return;
    pushRevalidationTraceEntry({
      segmentId: segment.id,
      segmentType: segment.type,
      belongsToRoute: segment.belongsToRoute ?? false,
      source: traceSource ?? "segment-resolution",
      defaultShouldRevalidate: defaultVal,
      finalShouldRevalidate: finalVal,
      reason,
      customRevalidators: revalidations.length || undefined,
    });
  }

  // A floored seed can only be raised, never lowered (see `defaultOverride`).
  // Applied at every exit so one trace entry carries the real decision — a
  // second, contradicting entry would let flushRevalidationTrace count the
  // segment as both revalidated and skipped.
  const floorTrue = defaultOverride?.floor === true && defaultOverride.value;
  function decide(finalVal: boolean, reason: string): boolean {
    if (floorTrue && !finalVal) {
      pushTrace(defaultShouldRevalidate, true, `${reason}:floored`);
      return true;
    }
    pushTrace(defaultShouldRevalidate, finalVal, reason);
    return finalVal;
  }

  let defaultShouldRevalidate: boolean;
  let defaultReason: string;

  if (defaultOverride) {
    defaultShouldRevalidate = defaultOverride.value;
    defaultReason = defaultOverride.reason;
  } else if (request.method === "POST") {
    if (segment.type === "route") {
      defaultShouldRevalidate = true;
      defaultReason = "action:route-segment";
    } else if (segment.type === "loader") {
      defaultShouldRevalidate = true;
      defaultReason = "action:loader-segment";
    } else if (segment.belongsToRoute) {
      defaultShouldRevalidate = true;
      defaultReason = "action:belongs-to-route";
    } else {
      defaultShouldRevalidate = false;
      defaultReason = "action:parent-chain-skip";
    }
  } else {
    if (segment.type === "route") {
      const routeChanged = paramsChanged || searchChanged;
      defaultShouldRevalidate = routeChanged;
      defaultReason = paramsChanged
        ? "nav:params-changed"
        : searchChanged
          ? "nav:search-changed"
          : "nav:params-unchanged";
      if (routeChanged) {
        debugLog("revalidation", "route revalidating", {
          segmentId: segment.id,
          paramsChanged,
          searchChanged,
        });
      }
    } else if (segment.belongsToRoute && (paramsChanged || searchChanged)) {
      defaultShouldRevalidate = true;
      defaultReason = paramsChanged
        ? "nav:route-child-params-changed"
        : "nav:route-child-search-changed";
      debugLog("revalidation", "route child revalidating", {
        segmentId: segment.id,
        segmentType: segment.type,
        paramsChanged,
        searchChanged,
      });
    } else {
      defaultShouldRevalidate = false;
      defaultReason = "nav:non-route-skip";
      debugLog("revalidation", "non-route segment skipped by default", {
        segmentId: segment.id,
        segmentType: segment.type,
      });
    }
  }

  if (revalidations.length === 0) {
    if (defaultShouldRevalidate) {
      debugLog("revalidation", "default revalidate=true", {
        segmentId: segment.id,
        prevParams,
        nextParams,
      });
    } else {
      debugLog("revalidation", "default revalidate=false", {
        segmentId: segment.id,
      });
    }
    return decide(defaultShouldRevalidate, defaultReason);
  }

  const prevSegment = getPrevSegment ? await getPrevSegment() : null;

  let currentSuggestion = defaultShouldRevalidate;

  const toRouteName =
    routeKey && !isAutoGeneratedRouteName(routeKey) ? routeKey : undefined;
  const reqCtx = _getRequestContext();
  const prevRouteKey = reqCtx?._prevRouteKey;
  const fromRouteName =
    prevRouteKey && !isAutoGeneratedRouteName(prevRouteKey)
      ? prevRouteKey
      : undefined;

  const isActionFn = makeIsAction(actionContext?.actionId);

  for (const { name, fn } of revalidations) {
    let result: any;
    try {
      result = fn({
        currentParams: prevSegment?.params || prevParams, // Use segment params if available, else route params
        currentUrl: prevUrl,
        nextParams,
        nextUrl,
        defaultShouldRevalidate: currentSuggestion,
        context,
        // Segment metadata (which segment is being evaluated)
        segmentType: segment.type,
        layoutName: segment.layoutName,
        slotName: segment.slot,
        // Action context (only populated when triggered by server action)
        actionId: actionContext?.actionId,
        isAction: isActionFn,
        actionUrl: actionContext?.actionUrl,
        actionResult: actionContext?.actionResult,
        formData: actionContext?.formData,
        method: request.method,
        routeName: toRouteName,
        fromRouteName,
        toRouteName,
        stale,
      });
    } catch (error) {
      // A thrown Response is control flow (e.g. `throw redirect(...)`), not a
      // failure: re-throw it so the handler chokepoint (match-handlers.ts)
      // turns it into the intended redirect/response. This mirrors how that
      // catch special-cases `error instanceof Response`.
      if (error instanceof Response) throw error;
      // Fail open for genuine errors: a buggy user revalidate fn must not
      // collapse the whole entry's loader batch into a failed partial render.
      // Mirror the dynamic-tags fail-open in cache/cache-policy.ts: log and
      // defer to the current default decision, leaving currentSuggestion
      // unchanged. TODO: route through callOnError(phase "revalidation") once
      // evaluateRevalidation is given the onError seam (today the error only
      // reaches onError via the entry-collapse path in match-handlers.ts).
      console.error(
        `[revalidate] "${name}" threw for segment "${segment.id}"; using default decision:`,
        error,
      );
      continue;
    }

    // The revalidate fn contract (handler-context.ts) is SYNCHRONOUS: it must
    // return a boolean, a { defaultShouldRevalidate } object, or null/undefined.
    // A Promise-returning (async) fn matches none of the decision branches below
    // and silently falls through keeping the current default — a hard-to-find
    // misuse. We do NOT await it (that would change the sync contract); instead
    // we surface it as a dev-mode warning so the silent drop is diagnosable.
    // Mirrors defer.ts: gated to dev, stripped from production builds.
    if (
      process.env.NODE_ENV !== "production" &&
      result != null &&
      typeof (result as { then?: unknown }).then === "function"
    ) {
      console.warn(
        `[rango] revalidate fn "${name}" returned a Promise; revalidate ` +
          `functions must be synchronous (return a boolean, ` +
          `{ defaultShouldRevalidate }, or null/undefined). The async result ` +
          `was IGNORED and the default (${currentSuggestion}) was kept. ` +
          `Move async work into a loader instead.`,
      );
    }

    if (typeof result === "boolean") {
      debugLog("revalidation", "hard decision", {
        segmentId: segment.id,
        revalidator: name,
        revalidate: result,
      });
      return decide(result, `hard:${name}`);
    } else if (
      result &&
      typeof result === "object" &&
      "defaultShouldRevalidate" in result
    ) {
      currentSuggestion = result.defaultShouldRevalidate;
      debugLog("revalidation", "soft decision", {
        segmentId: segment.id,
        revalidator: name,
        revalidate: currentSuggestion,
      });
    } else if (result === null || result === undefined) {
      debugLog("revalidation", "deferred to current default", {
        segmentId: segment.id,
        revalidator: name,
        revalidate: currentSuggestion,
      });
    }
  }

  debugLog("revalidation", "final decision", {
    segmentId: segment.id,
    revalidate: currentSuggestion,
  });
  const softNames = revalidations.map((r) => r.name).join(",");
  return decide(currentSuggestion, `soft-chain:${softNames}`);
}
