/**
 * Router Revalidation Logic
 *
 * Evaluates whether segments should revalidate based on params, actions, and custom functions.
 */

import type { ResolvedSegment, HandlerContext, ActionRef } from "../types";
import type { ActionContext } from "./types";
import {
  debugLog,
  pushRevalidationTraceEntry,
  isTraceActive,
} from "./logging.js";
import type { RevalidationTraceEntry } from "./logging.js";
import { _getRequestContext } from "../server/request-context.js";
import { isAutoGeneratedRouteName } from "../route-name.js";
import { paramsEqual } from "./params-util.js";

/**
 * Resolve a server-action reference's stable id, mirroring how the action
 * boundary derives `actionContext.actionId` in `rsc/server-action.ts`
 * (`$id ?? $$id`): the file-path `$id` set by the expose-action-id plugin in a
 * production RSC build when present, otherwise React's `$$id`. Resolving both
 * the incoming `actionId` and the reference with the same precedence makes
 * `isAction()` form-agnostic across dev and production.
 */
function resolveActionRefId(ref: unknown): string | undefined {
  if (ref == null) return undefined;
  const r = ref as { $id?: unknown; $$id?: unknown };
  if (typeof r.$id === "string") return r.$id;
  if (typeof r.$$id === "string") return r.$$id;
  return undefined;
}

/**
 * Build the `isAction()` helper bound to the current action's id. Called with no
 * arguments it answers "is this request an action at all?" (any action) — `true`
 * during action handling, `false` on plain navigation. Called with one or more
 * action references it narrows to those: a single imported action, several
 * (variadic), or any export of a namespace import (`import * as Mod`). Returns
 * `false` when there is no action (plain navigation) or nothing matches.
 */
function makeIsAction(
  currentActionId: string | undefined,
): (...actions: ActionRef[]) => boolean {
  return (...actions: ActionRef[]): boolean => {
    if (!currentActionId) return false;
    // Bare isAction(): an action is in flight (currentActionId is set) and the
    // caller did not narrow to a specific action, so this is "any action".
    if (actions.length === 0) return true;
    for (const action of actions) {
      if (typeof action === "function") {
        if (resolveActionRefId(action) === currentActionId) return true;
      } else if (action && typeof action === "object") {
        // Namespace import: match any export of the module.
        for (const value of Object.values(action)) {
          if (resolveActionRefId(value) === currentActionId) return true;
        }
      }
    }
    return false;
  };
}

/**
 * Options for revalidation evaluation
 */
interface EvaluateRevalidationOptions<TEnv> {
  /** Current segment to evaluate */
  segment: ResolvedSegment;
  /** Previous route params (from route match, not segment) */
  prevParams: Record<string, string>;
  /** Lazy function to get previous segment if needed */
  getPrevSegment: (() => Promise<ResolvedSegment | undefined>) | null;
  /** Current request */
  request: Request;
  /** Previous URL */
  prevUrl: URL;
  /** Next URL */
  nextUrl: URL;
  /** Custom revalidation functions */
  revalidations: Array<{ name: string; fn: any }>;
  /** Current route key */
  routeKey: string;
  /** Handler context */
  context: HandlerContext<any, TEnv>;
  /** Action context if triggered by action */
  actionContext?: ActionContext;
  /** If true, this is a stale cache revalidation request */
  stale?: boolean;
  /** Trace source hint for the revalidation trace */
  traceSource?: RevalidationTraceEntry["source"];
  /**
   * Override the segment-type-derived default. When set, the value is used as
   * the seed `defaultShouldRevalidate` passed to user revalidate fns and the
   * reason flows into the trace. Callers use this when client-knowledge
   * (e.g. parallel slot not in clientSegmentIds) should dictate the seed
   * instead of the params/method-based heuristic.
   */
  defaultOverride?: { value: boolean; reason: string };
}

/**
 * Evaluate if a segment should revalidate using soft/hard decision pattern
 * Optimized to use prevParams directly and avoid building previous segments
 */
export async function evaluateRevalidation<TEnv>(
  options: EvaluateRevalidationOptions<TEnv>,
): Promise<boolean> {
  const {
    segment,
    prevParams,
    getPrevSegment,
    request,
    prevUrl,
    nextUrl,
    revalidations,
    routeKey,
    context,
    actionContext,
    stale,
    traceSource,
    defaultOverride,
  } = options;
  const nextParams = segment.params || {};
  const paramsChanged = !paramsEqual(nextParams, prevParams);
  const searchChanged = prevUrl.search !== nextUrl.search;

  function pushTrace(
    defaultVal: boolean,
    finalVal: boolean,
    reason: string,
  ): void {
    if (!isTraceActive()) return;
    pushRevalidationTraceEntry({
      segmentId: segment.id,
      segmentType: segment.type,
      belongsToRoute: segment.belongsToRoute ?? false,
      source: traceSource ?? "segment-resolution",
      defaultShouldRevalidate: defaultVal,
      finalShouldRevalidate: finalVal,
      reason,
      customRevalidators: revalidations.length || undefined,
    });
  }

  let defaultShouldRevalidate: boolean;
  let defaultReason: string;

  if (defaultOverride) {
    defaultShouldRevalidate = defaultOverride.value;
    defaultReason = defaultOverride.reason;
  } else if (request.method === "POST") {
    if (segment.type === "route") {
      defaultShouldRevalidate = true;
      defaultReason = "action:route-segment";
    } else if (segment.type === "loader") {
      defaultShouldRevalidate = true;
      defaultReason = "action:loader-segment";
    } else if (segment.belongsToRoute) {
      defaultShouldRevalidate = true;
      defaultReason = "action:belongs-to-route";
    } else {
      defaultShouldRevalidate = false;
      defaultReason = "action:parent-chain-skip";
    }
  } else {
    if (segment.type === "route") {
      const routeChanged = paramsChanged || searchChanged;
      defaultShouldRevalidate = routeChanged;
      defaultReason = paramsChanged
        ? "nav:params-changed"
        : searchChanged
          ? "nav:search-changed"
          : "nav:params-unchanged";
      if (routeChanged) {
        debugLog("revalidation", "route revalidating", {
          segmentId: segment.id,
          paramsChanged,
          searchChanged,
        });
      }
    } else if (segment.belongsToRoute && (paramsChanged || searchChanged)) {
      defaultShouldRevalidate = true;
      defaultReason = paramsChanged
        ? "nav:route-child-params-changed"
        : "nav:route-child-search-changed";
      debugLog("revalidation", "route child revalidating", {
        segmentId: segment.id,
        segmentType: segment.type,
        paramsChanged,
        searchChanged,
      });
    } else {
      defaultShouldRevalidate = false;
      defaultReason = "nav:non-route-skip";
      debugLog("revalidation", "non-route segment skipped by default", {
        segmentId: segment.id,
        segmentType: segment.type,
      });
    }
  }

  if (revalidations.length === 0) {
    if (defaultShouldRevalidate) {
      debugLog("revalidation", "default revalidate=true", {
        segmentId: segment.id,
        prevParams,
        nextParams,
      });
    } else {
      debugLog("revalidation", "default revalidate=false", {
        segmentId: segment.id,
      });
    }
    pushTrace(defaultShouldRevalidate, defaultShouldRevalidate, defaultReason);
    return defaultShouldRevalidate;
  }

  const prevSegment = getPrevSegment ? await getPrevSegment() : null;

  let currentSuggestion = defaultShouldRevalidate;

  const toRouteName =
    routeKey && !isAutoGeneratedRouteName(routeKey) ? routeKey : undefined;
  const reqCtx = _getRequestContext();
  const prevRouteKey = reqCtx?._prevRouteKey;
  const fromRouteName =
    prevRouteKey && !isAutoGeneratedRouteName(prevRouteKey)
      ? prevRouteKey
      : undefined;

  for (const { name, fn } of revalidations) {
    const result = fn({
      currentParams: prevSegment?.params || prevParams, // Use segment params if available, else route params
      currentUrl: prevUrl,
      nextParams,
      nextUrl,
      defaultShouldRevalidate: currentSuggestion,
      context,
      // Segment metadata (which segment is being evaluated)
      segmentType: segment.type,
      layoutName: segment.layoutName,
      slotName: segment.slot,
      // Action context (only populated when triggered by server action)
      actionId: actionContext?.actionId,
      isAction: makeIsAction(actionContext?.actionId),
      actionUrl: actionContext?.actionUrl,
      actionResult: actionContext?.actionResult,
      formData: actionContext?.formData,
      method: request.method,
      routeName: toRouteName,
      fromRouteName,
      toRouteName,
      stale,
    });

    if (typeof result === "boolean") {
      debugLog("revalidation", "hard decision", {
        segmentId: segment.id,
        revalidator: name,
        revalidate: result,
      });
      pushTrace(defaultShouldRevalidate, result, `hard:${name}`);
      return result;
    } else if (
      result &&
      typeof result === "object" &&
      "defaultShouldRevalidate" in result
    ) {
      currentSuggestion = result.defaultShouldRevalidate;
      debugLog("revalidation", "soft decision", {
        segmentId: segment.id,
        revalidator: name,
        revalidate: currentSuggestion,
      });
    } else if (result === null || result === undefined) {
      debugLog("revalidation", "deferred to current default", {
        segmentId: segment.id,
        revalidator: name,
        revalidate: currentSuggestion,
      });
    }
  }

  debugLog("revalidation", "final decision", {
    segmentId: segment.id,
    revalidate: currentSuggestion,
  });
  const softNames = revalidations.map((r) => r.name).join(",");
  pushTrace(
    defaultShouldRevalidate,
    currentSuggestion,
    `soft-chain:${softNames}`,
  );
  return currentSuggestion;
}
