// Auto-generated by @rangojs/router - do not edit
export const routes = {
  article: "/:slug",
  author: "/author/:authorSlug",
  "author.posts": "/author/:authorSlug/posts",
  index: "/",
} as const;
export type routes = typeof routes;
