/**
 * A4: route(name, ...) must reject names that collide with reserved internal
 * prefixes ($path_, $prefix_), the same way path() and include() do via
 * validateUserRouteName. Without this guard such a name type-checks on an
 * untyped router and then silently vanishes from generated route-types and
 * public reverse() (isAutoGeneratedRouteName filters it out), so the consumer's
 * route disappears with no error.
 */
import { describe, it, expect } from "vitest";
import { RangoContext, type EntryData } from "../../server/context.js";
import { route } from "../dsl-helpers.js";

/** A parent entry shaped enough for route() to attach to. */
function parentEntry(): EntryData {
  return {
    id: "test",
    shortCode: "L0",
    type: "layout",
    parent: null,
    handler: null,
    loading: undefined,
    middleware: [],
    revalidate: [],
    errorBoundary: [],
    notFoundBoundary: [],
    layout: [],
    parallel: {},
    intercept: [],
    loader: [],
  } as unknown as EntryData;
}

/** Run `fn` inside a fresh DSL build context with the given parent. */
function withDslStore<T>(parent: EntryData, fn: () => T): T {
  return RangoContext.run(
    {
      manifest: new Map(),
      namespace: "test",
      parent,
      counters: {},
      patterns: new Map(),
    } as never,
    fn,
  );
}

// A minimal handler stand-in; route() only stores the reference.
const handler = (() => null) as never;

describe("route() name validation (A4)", () => {
  it("rejects a name using the reserved $prefix_ prefix", () => {
    withDslStore(parentEntry(), () => {
      expect(() => route("$prefix_0", handler)).toThrow(/reserved internal/i);
    });
  });

  it("rejects a name using the reserved $path_ prefix", () => {
    withDslStore(parentEntry(), () => {
      expect(() => route("$path_x", handler)).toThrow(/reserved internal/i);
    });
  });

  it("rejects a reserved prefix in any dot-segment", () => {
    withDslStore(parentEntry(), () => {
      expect(() => route("admin.$prefix_2", handler)).toThrow(
        /reserved internal/i,
      );
    });
  });

  it("accepts an ordinary name", () => {
    withDslStore(parentEntry(), () => {
      expect(() => route("products", handler)).not.toThrow();
    });
  });

  it("accepts a name that merely contains a $ (not a reserved prefix)", () => {
    withDslStore(parentEntry(), () => {
      expect(() => route("docs.$admin", handler)).not.toThrow();
    });
  });
});
