// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/about",
  "blog.index": "/blog",
  "blog.post": "/blog/:slug",
  counter: "/counter",
  dashboard: "/dashboard",
  feature: "/features/:slug",
  fetch: "/fetch",
  flash: "/flash",
  home: "/",
} as const;

// Aliased so the augmentation below does not pay a homomorphic mapped-type
// instantiation per route; `as const` already makes the members readonly.
type NamedRoutesShape = typeof NamedRoutes;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends NamedRoutesShape {}
  }
}
