// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  cache: "/cache",
  charts: "/charts",
  combined: "/combined",
  counter: "/counter",
  errBoom: "/errors/boom",
  errClientBoom: "/errors/client-boom",
  errGo: "/errors/go",
  errMissing: "/errors/missing",
  home: "/",
  hooks: "/hooks",
  login: "/login",
  "products.detail": "/products/:id",
  "products.index": "/products",
  search: { path: "/search", search: { q: "string?", page: "number?" } },
  secret: "/secret",
  state: "/state",
  widgets: "/widgets",
} as const;

// Aliased so the augmentation below does not pay a homomorphic mapped-type
// instantiation per route; `as const` already makes the members readonly.
type NamedRoutesShape = typeof NamedRoutes;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends NamedRoutesShape {}
  }
}
