// Auto-generated by @rangojs/router - do not edit
import type { Handler, DefaultEnv } from "@rangojs/router";

// Route name -> pattern mapping (generated from route definitions)
interface GeneratedRouteMap {
  "blog.index": "/blog";
  "blog.post": "/blog/:postId";
  "cacheStatus.notFound": "/cache-status/not-found";
  "cacheStatus.redirect": "/cache-status/redirect";
  "cacheStatus.redirectTarget": "/cache-status/redirect-target";
  "cacheStatus.serverError": "/cache-status/server-error";
  "cacheStatus.success": "/cache-status/success";
  "cacheTest.cachedLoader": "/cache-test/cached-loader";
  "cacheTest.interceptDetail": "/cache-test/intercept/:itemId";
  "cacheTest.interceptIndex": "/cache-test/intercept";
  "cacheTest.nonCachedLoader": "/cache-test/non-cached-loader";
  "cacheTest.useLoaderDetail": "/cache-test/useloader/:itemId";
  "cacheTest.useLoaderIndex": "/cache-test/useloader";
  "docs": "/docs";
  "docs.article": "/docs/:slug";
  "errors.clientError": "/errors/client-error";
  "errors.index": "/errors";
  "errors.serverError": "/errors/server-error";
  "errors.streamingError": "/errors/streaming-error";
  "fetchLoader": "/fetch-loader";
  "handlePassthrough": "/handle-passthrough";
  "handlePassthroughAsync": "/handle-passthrough-async";
  "hookTests.formAction": "/hook-tests/form-action";
  "hookTests.index": "/hook-tests";
  "hookTests.noLoader": "/hook-tests/no-loader";
  "hookTests.routeA": "/hook-tests/route-a";
  "hookTests.routeB": "/hook-tests/route-b";
  "href.detail": "/href/:id";
  "href.index": "/href";
  "href.nested.index": "/href/nested";
  "hydrationTest": "/hydration-test";
  "index": "/";
  "inlineAction": "/inline-action";
  "loaderComposition": "/loader-composition";
  "metaMerge.child": "/meta-merge/child";
  "metaMerge.deep": "/meta-merge/deep/nested";
  "metaMerge.index": "/meta-merge";
  "metaTemplate.absolute": "/meta-template/absolute";
  "metaTemplate.child": "/meta-template/child";
  "metaTemplate.index": "/meta-template";
  "metaTemplate.nested": "/meta-template/nested";
  "metaTemplate.nestedChild": "/meta-template/nested/child";
  "metaUnset.child": "/meta-unset/child";
  "metaUnset.index": "/meta-unset";
  "metaUnset.unsetThenSet": "/meta-unset/unset-then-set";
  "middlewareTest.cookies": "/middleware-test/cookies";
  "middlewareTest.errorHandler": "/middleware-test/error-handler/trigger";
  "middlewareTest.index": "/middleware-test";
  "middlewareTest.params": "/middleware-test/params/:paramId";
  "middlewareTest.protected": "/middleware-test/protected";
  "middlewareTest.protectedDashboard": "/middleware-test/protected/dashboard";
  "middlewareTest.routeLevel": "/middleware-test/route-level";
  "middlewareTest.routeLevelWithParams": "/middleware-test/route-level/:routeId";
  "middlewareTest.sharedVars": "/middleware-test/shared-vars";
  "proactiveCache.index": "/proactive-cache";
  "proactiveCache.itemA": "/proactive-cache/item-a";
  "proactiveCache.itemB": "/proactive-cache/item-b";
  "product.detail": "/product/:productId";
  "progressiveEnhancement": "/progressive-enhancement";
  "refTest.bothProps": "/ref-test/both-props";
  "refTest.handleProp": "/ref-test/handle-prop";
  "refTest.loaderProp": "/ref-test/loader-prop";
  "slow": "/slow";
  "slowProduct.detail": "/slow-product/:productId";
  "slowStreaming": "/slow-streaming";
  "slowStreamingSkipSsr": "/slow-streaming-skip-ssr";
  "theme.index": "/theme";
  "theme.toggle": "/theme/toggle";
  "trailingSlash.always": "/ts-always";
  "trailingSlash.ignore": "/ts-ignore";
  "trailingSlash.never": "/ts-never";
}

// Type-safe handler for a named route
export type HandlerFor<
  TRouteName extends keyof GeneratedRouteMap,
  TEnv = DefaultEnv,
> = Handler<GeneratedRouteMap[TRouteName], TEnv>;
