// Auto-generated by @rangojs/router - do not edit
export const routes = {
  index: "/",
  "product.detail": "/product/:productId",
  "slowProduct.detail": "/slow-product/:productId",
} as const;
export type routes = typeof routes;
