// Auto-generated by @rangojs/router - do not edit
export const routes = {
  index: "/",
  negotiateJsonFirst: "/negotiate-test-json-first",
  negotiateJsonFirstRsc: "/negotiate-test-json-first",
  negotiateTest: "/negotiate-test",
  negotiateTestJson: "/negotiate-test",
  "product.detail": "/product/:productId",
  responseInLayout: "/response-in-layout",
  responseMwNested: "/response-mw/nested",
  responseWrapHtml: "/response-wrap/html",
  responseWrapJsonHeaders: "/response-wrap/json-headers",
  responseWrapText: "/response-wrap/text",
  responseWrapXml: "/response-wrap/xml",
  shopPlayground: "/shop-playground",
  "slowProduct.detail": "/slow-product/:productId",
} as const;
export type routes = typeof routes;
