// Auto-generated by @rangojs/router - do not edit
export const routes = {
  benchFirst: "/bench/first",
  benchLast: "/bench/last",
  localeHome: "/",
} as const;
export type routes = typeof routes;
