import { isAbsolute, relative } from "node:path";
import { isAutoGeneratedRouteName } from "../../route-name.js";
import type {
  RouteKind,
  RouteRecord,
  RouterRecord,
} from "../../devtools-mcp/protocol.js";
import type { DiscoveryState } from "./state.js";

const MAX_ROUTE_FIELD_LENGTH = 4_096;
const MAX_ROUTER_FIELD_LENGTH = 1_024;
const MAX_SEARCH_ENTRIES = 64;
const MAX_SEARCH_FIELD_LENGTH = 256;

function bounded(value: string, limit: number): [string, boolean] {
  const encoded = Buffer.from(value, "utf8");
  if (encoded.byteLength <= limit) return [value, false];
  return [
    `${encoded
      .subarray(0, limit - 3)
      .toString("utf8")
      .replace(/\ufffd$/u, "")}...`,
    true,
  ];
}

function routeKind(pattern: string): RouteKind {
  if (pattern.includes("*")) return "wildcard";
  if (pattern.includes(":")) return "parameterized";
  return "static";
}

function projectRelativeFile(
  projectRoot: string,
  sourceFile: string | undefined,
): string | null {
  if (!sourceFile) return null;
  const result = relative(projectRoot, sourceFile);
  if (result === "" || result.startsWith("..") || isAbsolute(result)) {
    return null;
  }
  return result.replaceAll("\\", "/");
}

export function createMcpRouteSnapshot(state: DiscoveryState): RouteRecord[] {
  const routes: RouteRecord[] = [];

  for (const router of state.perRouterManifests) {
    const projectedRouterFile = projectRelativeFile(
      state.projectRoot,
      router.sourceFile,
    );
    const routerFile =
      projectedRouterFile === null
        ? null
        : bounded(projectedRouterFile, MAX_ROUTER_FIELD_LENGTH);
    for (const [internalName, pattern] of Object.entries(
      router.routeManifest,
    )) {
      let truncated = routerFile?.[1] ?? false;
      const [routerId, routerIdTruncated] = bounded(
        router.id,
        MAX_ROUTER_FIELD_LENGTH,
      );
      const [routePattern, patternTruncated] = bounded(
        pattern,
        MAX_ROUTE_FIELD_LENGTH,
      );
      const routeName = isAutoGeneratedRouteName(internalName)
        ? null
        : bounded(internalName, MAX_ROUTE_FIELD_LENGTH);
      const searchEntries = Object.entries(
        router.routeSearchSchemas?.[internalName] ?? {},
      );
      const search = Object.fromEntries(
        searchEntries.slice(0, MAX_SEARCH_ENTRIES).map(([key, value]) => {
          const [boundedKey, keyTruncated] = bounded(
            key,
            MAX_SEARCH_FIELD_LENGTH,
          );
          const [boundedValue, valueTruncated] = bounded(
            value,
            MAX_SEARCH_FIELD_LENGTH,
          );
          truncated ||= keyTruncated || valueTruncated;
          return [boundedKey, boundedValue];
        }),
      );
      truncated ||=
        routerIdTruncated ||
        patternTruncated ||
        routeName?.[1] === true ||
        searchEntries.length > MAX_SEARCH_ENTRIES;
      routes.push({
        routerId,
        routerFile: routerFile?.[0] ?? null,
        name: routeName?.[0] ?? null,
        pattern: routePattern,
        kind: routeKind(pattern),
        trailingSlash: router.routeTrailingSlash?.[internalName] ?? null,
        search: searchEntries.length === 0 ? null : search,
        truncated,
      });
    }
  }

  return routes;
}

export function createMcpRouterSnapshot(state: DiscoveryState): RouterRecord[] {
  return state.perRouterManifests.map((router) => {
    const file = projectRelativeFile(state.projectRoot, router.sourceFile);
    return {
      id: bounded(router.id, MAX_ROUTER_FIELD_LENGTH)[0],
      file: file === null ? null : bounded(file, MAX_ROUTER_FIELD_LENGTH)[0],
    };
  });
}
