/**
 * Deterministic generator for the sibling async-include groups under
 * src/groups/. Run manually, commit the output:
 *
 *   node scripts/gen-groups.mjs --groups 50
 *
 * Emits:
 *   src/groups/group-001.ts .. group-NNN.ts  (thin: default-export a factory call)
 *   src/groups/hub.ts                        (one async include() per group)
 *
 * The hub is itself mounted as ONE async include at /g in src/urls.tsx, so
 * the first /g/* request imports the hub chunk, splices N nested async
 * entries, then imports only the group actually hit — the many-sibling
 * nested-async-include path. Each thunk specifier is a literal string so
 * Rollup chunks per group and the AST fallback can follow the imports.
 */
import { mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";

const { values: args } = parseArgs({
  options: { groups: { type: "string", default: "50" } },
});
const groupCount = parseInt(args.groups, 10);
if (!Number.isInteger(groupCount) || groupCount < 1 || groupCount > 999) {
  console.error(`Invalid --groups "${args.groups}" (expected 1..999)`);
  process.exit(1);
}

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const groupsDir = path.join(root, "src", "groups");
mkdirSync(groupsDir, { recursive: true });

// Remove previously generated group files so lowering --groups leaves no orphans
for (const entry of readdirSync(groupsDir)) {
  if (/^group-\d{3}\.ts$/.test(entry) || entry === "hub.ts") {
    rmSync(path.join(groupsDir, entry));
  }
}

const header = `// GENERATED by scripts/gen-groups.mjs — do not edit; rerun the script.\n`;

const ids = [];
for (let i = 1; i <= groupCount; i++) {
  const id = `g${String(i).padStart(3, "0")}`;
  ids.push(id);
  writeFileSync(
    path.join(groupsDir, `group-${String(i).padStart(3, "0")}.ts`),
    `${header}import { makeRouteGroup } from "../stress/factory.js";\n\nconst group = makeRouteGroup("${id}");\n\nexport default group;\n`,
  );
}

const includes = ids
  .map(
    (id, i) =>
      `  include("/${id}", () => import("./group-${String(i + 1).padStart(3, "0")}.js"), {\n    name: "${id}",\n  }),`,
  )
  .join("\n");

// Wide UrlPatterns annotation: keeps the root urls() in urls.tsx from
// inferring through all groups (see makeRouteGroup's return-type comment).
writeFileSync(
  path.join(groupsDir, "hub.ts"),
  `${header}import { urls, type UrlPatterns } from "@rangojs/router";\n\nexport const hubPatterns: UrlPatterns<any> = urls(({ include }) => [\n${includes}\n]);\n\nexport default hubPatterns;\n`,
);

console.log(`Generated ${groupCount} group modules + hub.ts in src/groups/`);
