// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  "api.status": "/api/status",
  home: "/",
  users: "/users",
} as const;

declare global {
  namespace RSCRouter {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
