import { expect, test } from "@playwright/test";
import { execSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { useFixture } from "./fixture";

const genFilePath = path.resolve(
  "./e2e/test-app/src/router.named-routes.gen.ts",
);
const blogGenPath = path.resolve("./e2e/test-app/src/urls/blog.gen.ts");
const hrefGenPath = path.resolve("./e2e/test-app/src/urls/href.gen.ts");

test.describe("route-types", () => {
  test("should generate named-routes file on startup", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    // File should have the auto-generated header
    expect(content).toContain("// Auto-generated by @rangojs/router");

    // Should declare the global augmentation
    expect(content).toContain("namespace Rango");
    expect(content).toContain("interface GeneratedRouteMap");

    // Should export NamedRoutes and contain known routes from the test app
    expect(content).toContain("export const NamedRoutes");
    expect(content).toContain('index: "/",');
    expect(content).toContain('"blog.index": "/blog",');
    expect(content).toContain('"blog.post": "/blog/:postId",');
    expect(content).toContain('"product.detail": "/product/:productId",');
  });

  test("should contain all named routes from the app", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    // Count route entries (lines matching `  key: "pattern",` or `  "key": "pattern",`)
    const routeLines = content.match(/^\s+["a-zA-Z_$][^:]*: "[^"]+",$/gm);
    expect(routeLines).not.toBeNull();
    // The test app has many routes; verify at least a reasonable count
    expect(routeLines!.length).toBeGreaterThanOrEqual(30);
  });

  test("should not have double-slash patterns from include('/')", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    // Routes from include("/", patterns) should not produce "//path" patterns.
    // The prefix "/" is a root mount and should be a no-op.
    const doubleSlashLines = content.match(/: "\/\//gm);
    expect(doubleSlashLines).toBeNull();
  });
});

test.describe("per-module gen files", () => {
  test("should generate blog.gen.ts with correct routes", async () => {
    const content = await fs.readFile(blogGenPath, "utf-8");

    expect(content).toContain("// Auto-generated by @rangojs/router");
    expect(content).toContain('index: "/"');
    expect(content).toContain('post: "/:postId"');
    // Should export as const for runtime access + type alias
    expect(content).toContain("as const");
    expect(content).toContain("export type routes = typeof routes");
  });

  test("should not contain duplicate entries", async () => {
    const content = await fs.readFile(blogGenPath, "utf-8");

    // Each route name should appear exactly once
    const indexMatches = content.match(/index:/g);
    const postMatches = content.match(/post:/g);
    expect(indexMatches).toHaveLength(1);
    expect(postMatches).toHaveLength(1);
  });
});

test.describe("per-module gen files (href with search schema)", () => {
  test("should generate href.gen.ts via npx rango generate", async () => {
    // Run the CLI to regenerate — verifies the generate command works end-to-end
    execSync("npx rango generate e2e/test-app/src/urls/href.tsx", {
      cwd: path.resolve("."),
      stdio: "pipe",
    });

    const content = await fs.readFile(hrefGenPath, "utf-8");

    expect(content).toContain("// Auto-generated by @rangojs/router");
    expect(content).toContain("as const");
    expect(content).toContain("export type routes = typeof routes");

    // Simple string routes
    expect(content).toContain('index: "/"');
    expect(content).toContain('detail: "/:id"');

    // Route with params + search schema should be an object entry
    expect(content).toContain("filtered:");
    expect(content).toContain('path: "/filtered/:category"');
    expect(content).toContain('q: "string"');
    expect(content).toContain('page: "number?"');
    expect(content).toContain('active: "boolean?"');
  });

  test("should include href.filtered in global named-routes with search schema", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    // The global file should have the fully-qualified route with path prefix applied
    expect(content).toContain('"href.filtered"');
    expect(content).toContain('path: "/href/filtered/:category"');
    expect(content).toContain('q: "string"');
  });
});

test.describe("route-types (production)", () => {
  test("should generate named-routes file during build", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    expect(content).toContain("// Auto-generated by @rangojs/router");
    expect(content).toContain("export const NamedRoutes");
    expect(content).toContain('index: "/",');
    expect(content).toContain('"blog.index": "/blog",');
    expect(content).toContain('"blog.post": "/blog/:postId",');

    const routeLines = content.match(/^\s+["a-zA-Z_$][^:]*: "[^"]+",$/gm);
    expect(routeLines).not.toBeNull();
    expect(routeLines!.length).toBeGreaterThanOrEqual(30);
  });
});

// ---------------------------------------------------------------------------
// Unnamed routes: auto-generated $path names excluded from gen file,
// but routes still serve content at runtime.
// ---------------------------------------------------------------------------

test.describe("unnamed routes", () => {
  const f = useFixture({ root: "./e2e/test-app", mode: "dev" });

  test("gen file should not contain auto-generated $path route names", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    // Routes without an explicit name: property get auto-generated names
    // starting with "$" at runtime. These should be filtered from the gen
    // file to prevent HMR oscillation between static and runtime writers.
    const dollarRoutes = content.match(/"\$path/gm);
    expect(dollarRoutes).toBeNull();
  });

  test("unnamed route serves JSON content", async ({ request }) => {
    // The /__debug/reverse-test endpoint is an unnamed path.json() route.
    // It should respond correctly even though it's excluded from the gen file.
    const res = await request.get(
      f.url("/__debug/reverse-test?name=index&name=blog.index"),
    );
    expect(res.status()).toBe(200);
    expect(res.headers()["content-type"]).toContain("application/json");

    const body = await res.json();
    expect(body.data.index).toBe("/");
    expect(body.data["blog.index"]).toBe("/blog");
  });
});

test.describe("unnamed routes (production)", () => {
  const f = useFixture({ root: "./e2e/test-app", mode: "build" });

  test("gen file should not contain auto-generated $path route names", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    const dollarRoutes = content.match(/"\$path/gm);
    expect(dollarRoutes).toBeNull();
  });

  test("unnamed route serves JSON content", async ({ request }) => {
    const res = await request.get(
      f.url("/__debug/reverse-test?name=index&name=blog.index"),
    );
    expect(res.status()).toBe(200);
    expect(res.headers()["content-type"]).toContain("application/json");

    const body = await res.json();
    expect(body.data.index).toBe("/");
    expect(body.data["blog.index"]).toBe("/blog");
  });
});
