import { expect, test } from "@playwright/test";
import fs from "node:fs/promises";
import path from "node:path";

const genFilePath = path.resolve(
  "./e2e/test-app/src/named-routes.router_0.gen.ts"
);

test.describe("route-types", () => {
  test("should generate named-routes file on startup", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    // File should have the auto-generated header
    expect(content).toContain("// Auto-generated by @rangojs/router");

    // Should declare the global augmentation
    expect(content).toContain("namespace RSCRouter");
    expect(content).toContain("interface GeneratedRouteMap");

    // Should contain known routes from the test app
    expect(content).toContain('"index": "/"');
    expect(content).toContain('"blog.index": "/blog"');
    expect(content).toContain('"blog.post": "/blog/:postId"');
    expect(content).toContain('"product.detail": "/product/:productId"');
  });

  test("should contain all named routes from the app", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    // Count route entries (lines matching `"routeName": "pattern"`)
    const routeLines = content.match(/^\s+"[^"]+": "[^"]+";$/gm);
    expect(routeLines).not.toBeNull();
    // The test app has many routes; verify at least a reasonable count
    expect(routeLines!.length).toBeGreaterThanOrEqual(30);
  });
});

test.describe("route-types (production)", () => {
  test("should generate named-routes file during build", async () => {
    const content = await fs.readFile(genFilePath, "utf-8");

    expect(content).toContain("// Auto-generated by @rangojs/router");
    expect(content).toContain('"index": "/"');
    expect(content).toContain('"blog.index": "/blog"');
    expect(content).toContain('"blog.post": "/blog/:postId"');

    const routeLines = content.match(/^\s+"[^"]+": "[^"]+";$/gm);
    expect(routeLines).not.toBeNull();
    expect(routeLines!.length).toBeGreaterThanOrEqual(30);
  });
});
