// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/about",
  blog: "/blog",
  "blog.detail": "/blog/:slug",
  cards: "/cards",
  "cards.detail": "/cards/:slug",
  counter: "/counter",
  home: "/",
  "layoutTx.a": "/layout-tx-a",
  "layoutTx.b": "/layout-tx-b",
  prerender: "/prerender",
  "prerender.article": "/prerender/:slug",
  static: "/static",
  "transition.a": "/transition-a",
  "transition.b": "/transition-b",
} as const;

declare global {
  namespace RSCRouter {
    interface GeneratedRouteMap extends Readonly<typeof NamedRoutes> {}
  }
}
