// Auto-generated by @rangojs/router - do not edit
export const NamedRoutes = {
  about: "/about",
  blog: "/blog",
  "blog.detail": "/blog/:slug",
  cards: "/cards",
  "cards.detail": "/cards/:slug",
  counter: "/counter",
  home: "/",
  "layoutTx.a": "/layout-tx-a",
  "layoutTx.b": "/layout-tx-b",
  "plainProduct.detail": "/plain-product/:id",
  prerender: "/prerender",
  "prerender.article": "/prerender/:slug",
  refresh: "/refresh",
  static: "/static",
  streamTestDetail: "/stream-test/:id",
  streamTestIndex: "/stream-test",
  "swrProduct.detail": "/swr-product/:id",
  "transition.a": "/transition-a",
  "transition.b": "/transition-b",
  "vt.auto.x": "/vt-auto-x",
  "vt.auto.y": "/vt-auto-y",
  "vt.forceAuto.x": "/vt-force-auto-x",
  "vt.forceAuto.y": "/vt-force-auto-y",
  "vt.off.x": "/vt-off-x",
  "vt.off.y": "/vt-off-y",
  "vt.user.x": "/vt-user-x",
  "vt.user.y": "/vt-user-y",
} as const;

// Aliased so the augmentation below does not pay a homomorphic mapped-type
// instantiation per route; `as const` already makes the members readonly.
type NamedRoutesShape = typeof NamedRoutes;

declare global {
  namespace Rango {
    interface GeneratedRouteMap extends NamedRoutesShape {}
  }
}
